import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {randomUUID} from 'node:crypto';
const root=new URL('../',import.meta.url).href;const {createDb}=await import(root+'src/db.js');const {createOwnedDb}=await import(root+'test/stage5OwnedDb.js');const {fixtureKeys}=await import(root+'test/localDb.js');const {hranaTransport}=await import(root+'test/hranaTransport.js');const {makeDataset}=await import(root+'test/fixtures.js');const {fakeCoach}=await import(root+'test/fakes.js');const {staticDataSource}=await import(root+'src/dataSource.js');const {WHOOP_SYNC}=await import(root+'src/config.js');
const {runExecutionPhase}=await import(root+'src/phase4Execution.js');const {configurationProof}=await import(root+'src/phase4ExecutionStore.js');const {publicBetaConfiguration}=await import(root+'src/publicBetaConfig.js');const {runningReleaseSha}=await import(root+'src/phase4Release.js');const {RECONCILE_RESULT}=await import(root+'src/schema.js');
for(const shadow of ['off','on'])test(`three saved languages preserve daily delivery and zero replay sends with SHADOW ${shadow}/presentation OFF`,async t=>{
 const now=new Date('2026-10-09T00:00:00Z'),ids=['alice','bob','lan'],locales=['zh-TW','en','vi'],names=['REVIEW_ALICE','REVIEW_BOB','REVIEW_LAN'],data=new Map();
 const dir=await mkdtemp('/private/tmp/rc4-three-language-'),url=`file:${join(dir,'db.sqlite')}`,seed=createOwnedDb({url});await seed.migrate({targetVersion:32});
 for(const [i,id] of ids.entries()){
  await seed.createUser({id,displayName:names[i],status:'ACTIVE',timezone:'Asia/Taipei'});await seed.setLocale(id,locales[i]);await seed.linkTelegram({userId:id,chatId:String(1001+i)});
  await seed.saveTokens(id,{accessToken:'synthetic',refreshToken:'synthetic',expiresAt:new Date(Date.now()+3600000),whoopUserId:String(12345+i)});await seed.saveCapabilities(id,[{key:'sleep',status:'SUPPORTED'}],{expectedLifecycleGeneration:1});
  data.set(id,makeDataset({now,days:45,withNaps:false,seed:42+i,overrides:{0:{hrv:60+i*30}}}));
  for(const resource of WHOOP_SYNC.RESOURCES){await seed.saveSyncState(id,resource,{backfillComplete:true,lastSuccessAt:now.toISOString()},{now});const owner='seed-'+id+'-'+resource;assert.equal(await seed.claimReconciliation({userId:id,resource,owner,leaseMs:300000,now,lifecycleGeneration:1}),true);assert.equal(await seed.settleReconciliation({userId:id,resource,owner,result:RECONCILE_RESULT.SUCCESS,windowTo:now,now,lifecycleGeneration:1}),true);}
 }
 await seed.close();const transport=hranaTransport(url),db=createDb({url:'https://isolated.invalid',phase4Keys:fixtureKeys,fetch:transport.fetch});t.after(async()=>{db.close();transport.close();await rm(dir,{recursive:true,force:true});});
 const environment={PHASE4_BETA_SHADOW_RUNTIME:shadow,PHASE4_PUBLIC_BETA_MODE:'off'},request={releaseSha:runningReleaseSha(),requestId:randomUUID(),phase:'SYNC',triggerSource:'cloudflare',executionMode:shadow==='on'?'SHADOW':'OFF',configProof:configurationProof(fixtureKeys,publicBetaConfiguration(environment),environment)};
 const payloads=[],env={timezone:'Asia/Taipei',dryRun:true,maxUserConcurrency:3,telegramBotToken:'synthetic',telegramChatId:'synthetic',whoopClientId:'synthetic',whoopClientSecret:'synthetic',openrouterApiKey:'synthetic',openrouterModel:'synthetic',repoLastCommitAt:now.toISOString()};
 const deps={makeWhoop:({userId})=>({userId,getAccessToken:async()=>'synthetic'}),makeSource:({whoop})=>staticDataSource(data.get(whoop.userId)),makeCoach:()=>fakeCoach(),makeTelegram:({chatId,locale})=>({send:async text=>{payloads.push({chatId,locale,text});return {messageId:payloads.length};},sendTyping:async()=>true,notifyError:async()=>false}),proactive:async()=>null,guardian:async()=>null,predictionCycle:async()=>null,healthspan:async()=>null};
 const run=r=>runExecutionPhase({request:r,db,keys:fixtureKeys,environment,env,deps,now});const first=await run(request);assert.equal(first.status,200,JSON.stringify(first));assert.equal(payloads.length,3);
 for(const [i,id] of ids.entries()){const p=payloads.find(p=>p.chatId===String(1001+i));assert.equal(p.locale,locales[i]);assert.ok(p.text.includes(names[i]));for(const name of names.filter(x=>x!==names[i]))assert.ok(!p.text.includes(name));assert.doesNotMatch(p.text,/Body Energy|Beta Summary|Kelvin/);if(locales[i]!=='zh-TW')assert.doesNotMatch(p.text,/[\u3400-\u9fff]/u);}
 assert.deepEqual(await run(request),first);assert.equal(payloads.length,3);assert.equal((await run({...request,requestId:randomUUID()})).status,200);assert.equal(payloads.length,3);
 const claims=(await db.raw.execute("SELECT user_id,local_date,delivery_state,delivery_attempts,telegram_message_id FROM report_claims WHERE report_type='daily' ORDER BY user_id")).rows.map(r=>({...r}));assert.equal(claims.length,3);assert.ok(claims.every(r=>r.delivery_state==='DELIVERED'&&r.delivery_attempts===1&&r.telegram_message_id!==null));assert.equal((await db.raw.execute("SELECT count(*) n FROM report_runs WHERE report_type='daily' AND status='SENT'")).rows[0].n,3);
 console.log('REVIEW_DELIVERY '+JSON.stringify({locales,claims,delivered:payloads.length,cachedReplayAdditional:0,freshIdentityReplayAdditional:0,bodyEnergy:'NOT_AUTHORIZED_NOT_PRESENTED'}));
});
