/** Deterministic answer copy; every key is required in all three catalogs. */
export const ANSWER_EXTRA_CATALOG = Object.freeze({
  'zh-TW': {
    'answer.metricUnknown':'這個指標', 'answer.metric.sleep_total':'睡眠', 'answer.metric.sleep_performance':'睡眠表現',
    'answer.metric.recovery':'恢復', 'answer.metric.hrv':'HRV', 'answer.metric.rhr':'靜息心率',
    'answer.metric.previous_day_strain':'昨日 Strain', 'answer.metric.deep_sleep':'深睡', 'answer.metric.rem_sleep':'REM',
    'answer.metric.respiratory_rate':'呼吸率', 'answer.metric.sleep_debt':'睡眠債',
    'answer.metric.spo2':'血氧', 'answer.metric.skin_temp':'皮膚溫度', 'answer.metric.current_hr':'即時心率',
    'answer.todayTitle':'📊 {date} 的狀態', 'answer.metricValue':'{metric} {value}',
    'answer.metricMissing':'{metric}：無資料', 'answer.baseline':'（基準 {value}）',
    'answer.trendTitle':'📈 {metric}', 'answer.current':'目前 {value}',
    'answer.calibrating':'（還在 WHOOP 校正期，暫時不做趨勢判斷）',
    'answer.insufficientHistory':'（樣本還太少，還不夠下結論）',
    'answer.windowMean':'{days} 天平均 {mean}（n={count}）',
    'answer.trendLine':'{days} 天趨勢：{direction}',
    'answer.trend.IMPROVING':'改善', 'answer.trend.STABLE':'持平',
    'answer.trend.DECLINING':'轉弱', 'answer.trend.INSUFFICIENT_DATA':'資料不足',
    'answer.bestTitle':'🏆 {metric}（最近 {days} 天，n={count}）',
    'answer.best':'最好：{date} {value}', 'answer.worst':'最差：{date} {value}',
    'answer.noChanges':'今天沒有特別值得注意的變化。',
    'answer.changesTitle':'🔎 今天最值得注意', 'answer.changeLine':'· {metric} {value}',
    'answer.sleepTitle':'🌙 睡眠（最近 {days} 天）',
    'answer.sleepLine':'{metric}：目前 {current}，平均 {mean}（n={count}）',
    'answer.unable':'目前無法回答這個問題。', 'answer.na':'無資料',
    'answer.causeWithFactor':'{factor}確實可能讓人短時間覺得疲倦，不過目前還不能確定這就是主因。',
    'answer.causeUnknown':'你會覺得累是一個事實，值得看一下 —— 不過我還沒辦法指出原因。',
    'answer.causeToday':'今天{observations}。', 'answer.causeObservation':'{metric} {value}{baseline}',
    'answer.causeBaselineNoteworthy':'（平常約 {value}，這次偏離比較明顯）',
    'answer.causeBaselineSimilar':'（平常約 {value}，差不多）',
    'answer.causeNoBaselineNamed':'不過{metrics}的個人基準還在累積，我沒辦法判斷這些數字是不是偏離你的常態。',
    'answer.causeNoBaseline':'不過你的個人基準還在累積，我沒辦法判斷這些數字是不是偏離你的常態。',
    'answer.causeSomeBaseline':'{metrics}的基準還在累積，那幾項我暫時不下判斷。',
    'answer.causeTiming':'而且今天的恢復與 HRV 是在這件事之前量到的，沒辦法用來看它的影響。',
    'answer.causeAdviceWithFactor':'先休息、補充水分並觀察。',
    'answer.causeAdvice':'先照平常的節奏休息，有變化再跟我說。',
    'answer.readinessYes':'對，主要是這個。', 'answer.readinessNo':'不完全是。',
    'answer.readinessTodayNamed':'今天的數字我看得到，但{metrics}還沒有足夠的合格歷史可以建立你的個人基準，所以我還不能可靠判斷它們是否偏離你平常的狀態。',
    'answer.readinessToday':'今天的數字我看得到，但合格的歷史還不夠建立你的個人基準。',
    'answer.readinessNoFacts':'我目前累積到的合格資料還太少，還建立不出你的個人基準。',
    'answer.readinessCalibrating':'WHOOP 本身也還在校正期，這段期間的數值不適合當基準。',
    'answer.readinessNeed':'做最基本的比較，每個指標大約需要 {count} 筆先前的合格紀錄；不同的判斷（趨勢、預測、關聯）需要的更多。',
    'answer.readinessCaveat':'再累積一段時間會好很多。不過就算歷史足夠，我能給的也是關聯，不是單一原因的證明。',
    'answer.readinessOther':'相關指標的基準我都已經建立得起來了。判斷不出來比較可能是因為：這件事的答案本來就不在 WHOOP 量得到的範圍裡，或是目前的數字確實沒有明顯偏離。',
  },
  en: {
    'answer.metricUnknown':'this metric', 'answer.metric.sleep_total':'Sleep', 'answer.metric.sleep_performance':'Sleep performance',
    'answer.metric.recovery':'Recovery', 'answer.metric.hrv':'HRV', 'answer.metric.rhr':'Resting heart rate',
    'answer.metric.previous_day_strain':'Yesterday’s Strain', 'answer.metric.deep_sleep':'Deep sleep', 'answer.metric.rem_sleep':'REM sleep',
    'answer.metric.respiratory_rate':'Respiratory rate', 'answer.metric.sleep_debt':'Sleep debt',
    'answer.metric.spo2':'Blood oxygen', 'answer.metric.skin_temp':'Skin temperature', 'answer.metric.current_hr':'Current heart rate',
    'answer.todayTitle':'📊 Your status for {date}', 'answer.metricValue':'{metric}: {value}',
    'answer.metricMissing':'{metric}: no data', 'answer.baseline':' (baseline {value})',
    'answer.trendTitle':'📈 {metric}', 'answer.current':'Current value: {value}',
    'answer.calibrating':'WHOOP is still calibrating, so I cannot assess a trend yet.',
    'answer.insufficientHistory':'There are too few samples to draw a conclusion yet.',
    'answer.windowMean':'{days}-day average: {mean} (n={count})',
    'answer.trendLine':'{days}-day trend: {direction}',
    'answer.trend.IMPROVING':'improving', 'answer.trend.STABLE':'stable',
    'answer.trend.DECLINING':'declining', 'answer.trend.INSUFFICIENT_DATA':'insufficient data',
    'answer.bestTitle':'🏆 {metric} (past {days} days, n={count})',
    'answer.best':'Best: {date} — {value}', 'answer.worst':'Lowest: {date} — {value}',
    'answer.noChanges':'Nothing stands out as a notable change today.',
    'answer.changesTitle':'🔎 Most notable changes today', 'answer.changeLine':'· {metric}: {value}',
    'answer.sleepTitle':'🌙 Sleep (past {days} days)',
    'answer.sleepLine':'{metric}: currently {current}, average {mean} (n={count})',
    'answer.unable':'I cannot answer that right now.', 'answer.na':'no data',
    'answer.causeWithFactor':'{factor} could contribute to short-term tiredness, but I cannot tell whether it is the main cause.',
    'answer.causeUnknown':'Feeling tired is real and worth paying attention to, though I cannot identify a cause yet.',
    'answer.causeToday':'Today: {observations}.', 'answer.causeObservation':'{metric} {value}{baseline}',
    'answer.causeBaselineNoteworthy':' (usually about {value}; this change is more pronounced)',
    'answer.causeBaselineSimilar':' (usually about {value}; fairly similar)',
    'answer.causeNoBaselineNamed':'Your personal baselines for {metrics} are still developing, so I cannot judge whether these readings differ from usual.',
    'answer.causeNoBaseline':'Your personal baselines are still developing, so I cannot judge whether these readings differ from usual.',
    'answer.causeSomeBaseline':'The baselines for {metrics} are still developing; I will not draw conclusions from those readings yet.',
    'answer.causeTiming':'Today’s Recovery and HRV were measured before that event, so they cannot show its effect.',
    'answer.causeAdviceWithFactor':'Rest, drink water, and keep an eye on how you feel.',
    'answer.causeAdvice':'Keep your usual rest routine and tell me if anything changes.',
    'answer.readinessYes':'Yes, that is the main limitation.', 'answer.readinessNo':'Not entirely.',
    'answer.readinessTodayNamed':'I can see today’s numbers, but there is not enough qualified history to build your personal baselines for {metrics}. I cannot reliably judge how unusual these readings are.',
    'answer.readinessToday':'I can see today’s numbers, but there is not enough qualified history to build your personal baselines.',
    'answer.readinessNoFacts':'I do not yet have enough qualified data to build your personal baselines.',
    'answer.readinessCalibrating':'WHOOP is also still calibrating, so readings from this period are not suitable as a baseline.',
    'answer.readinessNeed':'A basic comparison needs about {count} earlier qualified readings per metric. Trends, predictions, and associations need more.',
    'answer.readinessCaveat':'More history will help. Even with enough history, I can identify associations, not prove a single cause.',
    'answer.readinessOther':'I can build baselines for the relevant metrics. The answer may lie outside what WHOOP measures, or the current readings may not show a clear deviation.',
  },
  vi: {
    'answer.metricUnknown':'chỉ số này', 'answer.metric.sleep_total':'Giấc ngủ', 'answer.metric.sleep_performance':'Hiệu quả giấc ngủ',
    'answer.metric.recovery':'Phục hồi', 'answer.metric.hrv':'HRV', 'answer.metric.rhr':'Nhịp tim lúc nghỉ',
    'answer.metric.previous_day_strain':'Strain hôm qua', 'answer.metric.deep_sleep':'Ngủ sâu', 'answer.metric.rem_sleep':'Giấc ngủ REM',
    'answer.metric.respiratory_rate':'Nhịp thở', 'answer.metric.sleep_debt':'Nợ ngủ',
    'answer.metric.spo2':'Oxy máu', 'answer.metric.skin_temp':'Nhiệt độ da', 'answer.metric.current_hr':'Nhịp tim hiện tại',
    'answer.todayTitle':'📊 Tình trạng của bạn ngày {date}', 'answer.metricValue':'{metric}: {value}',
    'answer.metricMissing':'{metric}: chưa có dữ liệu', 'answer.baseline':' (mức cơ sở {value})',
    'answer.trendTitle':'📈 {metric}', 'answer.current':'Giá trị hiện tại: {value}',
    'answer.calibrating':'WHOOP vẫn đang hiệu chuẩn nên tôi chưa thể đánh giá xu hướng.',
    'answer.insufficientHistory':'Hiện có quá ít mẫu để đưa ra kết luận.',
    'answer.windowMean':'Trung bình {days} ngày: {mean} (n={count})',
    'answer.trendLine':'Xu hướng {days} ngày: {direction}',
    'answer.trend.IMPROVING':'cải thiện', 'answer.trend.STABLE':'ổn định',
    'answer.trend.DECLINING':'giảm sút', 'answer.trend.INSUFFICIENT_DATA':'chưa đủ dữ liệu',
    'answer.bestTitle':'🏆 {metric} (trong {days} ngày qua, n={count})',
    'answer.best':'Tốt nhất: {date} — {value}', 'answer.worst':'Thấp nhất: {date} — {value}',
    'answer.noChanges':'Hôm nay không có thay đổi nào đặc biệt đáng chú ý.',
    'answer.changesTitle':'🔎 Thay đổi đáng chú ý nhất hôm nay', 'answer.changeLine':'· {metric}: {value}',
    'answer.sleepTitle':'🌙 Giấc ngủ (trong {days} ngày qua)',
    'answer.sleepLine':'{metric}: hiện tại {current}, trung bình {mean} (n={count})',
    'answer.unable':'Hiện tôi chưa thể trả lời câu hỏi đó.', 'answer.na':'chưa có dữ liệu',
    'answer.causeWithFactor':'{factor} có thể góp phần khiến bạn mệt trong ngắn hạn, nhưng tôi chưa thể xác định đó là nguyên nhân chính.',
    'answer.causeUnknown':'Việc bạn thấy mệt là có thật và đáng quan tâm, dù tôi chưa thể xác định nguyên nhân.',
    'answer.causeToday':'Hôm nay: {observations}.', 'answer.causeObservation':'{metric} {value}{baseline}',
    'answer.causeBaselineNoteworthy':' (thường khoảng {value}; lần này lệch rõ hơn)',
    'answer.causeBaselineSimilar':' (thường khoảng {value}; khá tương tự)',
    'answer.causeNoBaselineNamed':'Mức cơ sở cá nhân của {metrics} vẫn đang được xây dựng, nên tôi chưa thể đánh giá các số liệu này có khác thường hay không.',
    'answer.causeNoBaseline':'Mức cơ sở cá nhân của bạn vẫn đang được xây dựng, nên tôi chưa thể đánh giá các số liệu này có khác thường hay không.',
    'answer.causeSomeBaseline':'Mức cơ sở của {metrics} vẫn đang được xây dựng; tôi chưa kết luận về các chỉ số đó.',
    'answer.causeTiming':'Chỉ số Phục hồi và HRV hôm nay được đo trước sự kiện đó, nên không thể cho thấy tác động của nó.',
    'answer.causeAdviceWithFactor':'Hãy nghỉ ngơi, uống nước và theo dõi cảm giác của bạn.',
    'answer.causeAdvice':'Hãy nghỉ ngơi theo nhịp sinh hoạt thường ngày và cho tôi biết nếu có gì thay đổi.',
    'answer.readinessYes':'Đúng, đó là hạn chế chính.', 'answer.readinessNo':'Không hoàn toàn.',
    'answer.readinessTodayNamed':'Tôi thấy các số liệu hôm nay, nhưng chưa có đủ lịch sử đạt chuẩn để xây dựng mức cơ sở cá nhân cho {metrics}. Vì vậy tôi chưa thể đánh giá tin cậy mức độ khác thường.',
    'answer.readinessToday':'Tôi thấy các số liệu hôm nay, nhưng chưa có đủ lịch sử đạt chuẩn để xây dựng mức cơ sở cá nhân.',
    'answer.readinessNoFacts':'Tôi chưa tích lũy đủ dữ liệu đạt chuẩn để xây dựng mức cơ sở cá nhân.',
    'answer.readinessCalibrating':'WHOOP cũng đang hiệu chuẩn, nên số liệu giai đoạn này không phù hợp làm mức cơ sở.',
    'answer.readinessNeed':'Một phép so sánh cơ bản cần khoảng {count} bản ghi đạt chuẩn trước đó cho mỗi chỉ số. Xu hướng, dự đoán và liên hệ cần nhiều hơn.',
    'answer.readinessCaveat':'Thêm lịch sử sẽ giúp ích. Dù đủ lịch sử, tôi chỉ có thể nhận ra mối liên hệ, không chứng minh một nguyên nhân duy nhất.',
    'answer.readinessOther':'Tôi đã có thể xây dựng mức cơ sở cho các chỉ số liên quan. Câu trả lời có thể nằm ngoài những gì WHOOP đo được, hoặc các số liệu hiện tại không lệch rõ.',
  },
});
