export const ANSWER_CATALOG = Object.freeze({
  'zh-TW': {
    'answer.agoMinutes':'{value} 分鐘前', 'answer.agoHours':'{value} 小時前',
    'answer.agoDays':'{value} 天前', 'answer.timeUnknown':'有紀錄但時間不明',
    'answer.latestDate':'目前最新的健康資料是 {date}。',
    'answer.latestDateCaveat':'目前最新的健康資料是 {date}，但那不保證最近一次同步成功。',
    'answer.sync.noNewData':'有，最近一次完整同步成功{ago}，不過還沒有今天的新資料。',
    'answer.sync.scoreWait':'WHOOP 通常要等當天的睡眠評分出來之後才會有新的數字。',
    'answer.sync.complete':'有，最近一次完整同步成功，時間{ago}。',
    'answer.sync.partial':'有部分資料同步成功{ago}，但不是每一項都確認拿到了，所以我沒辦法說這次是完整的。',
    'answer.sync.historicalFailure':'之前成功過{ago}，但最近一次有部分沒有成功。',
    'answer.sync.retryAuth':'通常下一次排程會自己補上；如果一直這樣，可能要重新授權一次 WHOOP。',
    'answer.sync.stale':'有成功過，但已經有一段時間沒有更新了{ago}。',
    'answer.sync.staleAdvice':'如果你的 WHOOP 有在配戴而且有連上網，通常下一次排程就會補上。',
    'answer.sync.failed':'目前看起來同步是失敗的，我這邊還沒有成功取得資料的紀錄。如果持續這樣，可能要重新授權一次 WHOOP。',
    'answer.sync.never':'我這邊還沒有任何同步紀錄，看起來同步從來沒有跑成功過。',
    'answer.sync.incomplete':'目前只能確認部分狀態 —— 我手邊的同步紀錄不完整，沒辦法確定最近一次的結果。',
  },
  en: {
    'answer.agoMinutes':'{value} minutes ago', 'answer.agoHours':'{value} hours ago',
    'answer.agoDays':'{value} days ago', 'answer.timeUnknown':'recorded, but the time is unknown',
    'answer.latestDate':'The latest health data is from {date}.',
    'answer.latestDateCaveat':'The latest health data is from {date}, but that does not prove the most recent sync succeeded.',
    'answer.sync.noNewData':'The last full sync succeeded{ago}, but there is no new data for today yet.',
    'answer.sync.scoreWait':'WHOOP usually provides new numbers after today’s sleep has been scored.',
    'answer.sync.complete':'The most recent full sync succeeded {ago}.',
    'answer.sync.partial':'Some data synced successfully{ago}, but I cannot confirm that every part arrived.',
    'answer.sync.historicalFailure':'A previous sync succeeded{ago}, but part of the most recent one failed.',
    'answer.sync.retryAuth':'The next scheduled check often fills the gap. If this continues, you may need to reconnect WHOOP.',
    'answer.sync.stale':'A sync succeeded before, but the data has not updated for a while{ago}.',
    'answer.sync.staleAdvice':'If you have been wearing WHOOP and it is connected, the next scheduled check may catch up.',
    'answer.sync.failed':'The latest sync appears to have failed, and I have no record of a successful data fetch. If this continues, you may need to reconnect WHOOP.',
    'answer.sync.never':'I have no sync record yet, so I cannot confirm that syncing has ever succeeded.',
    'answer.sync.incomplete':'I can confirm only part of the sync status. The records are incomplete, so I cannot determine the latest result.',
  },
  vi: {
    'answer.agoMinutes':'{value} phút trước', 'answer.agoHours':'{value} giờ trước',
    'answer.agoDays':'{value} ngày trước', 'answer.timeUnknown':'đã ghi nhận nhưng không rõ thời gian',
    'answer.latestDate':'Dữ liệu sức khỏe mới nhất là ngày {date}.',
    'answer.latestDateCaveat':'Dữ liệu sức khỏe mới nhất là ngày {date}, nhưng điều đó không chứng minh lần đồng bộ gần nhất thành công.',
    'answer.sync.noNewData':'Lần đồng bộ đầy đủ gần nhất đã thành công{ago}, nhưng hôm nay chưa có dữ liệu mới.',
    'answer.sync.scoreWait':'WHOOP thường có số liệu mới sau khi giấc ngủ hôm nay được chấm điểm.',
    'answer.sync.complete':'Lần đồng bộ đầy đủ gần nhất đã thành công {ago}.',
    'answer.sync.partial':'Một phần dữ liệu đã đồng bộ thành công{ago}, nhưng tôi chưa thể xác nhận mọi phần đều đã đến.',
    'answer.sync.historicalFailure':'Trước đây đã đồng bộ thành công{ago}, nhưng một phần lần gần nhất bị lỗi.',
    'answer.sync.retryAuth':'Lần kiểm tra theo lịch tiếp theo thường sẽ bổ sung dữ liệu. Nếu tình trạng tiếp diễn, bạn có thể cần kết nối lại WHOOP.',
    'answer.sync.stale':'Trước đây đã đồng bộ thành công, nhưng dữ liệu đã lâu chưa cập nhật{ago}.',
    'answer.sync.staleAdvice':'Nếu bạn vẫn đeo WHOOP và thiết bị có kết nối, lần kiểm tra theo lịch tiếp theo có thể cập nhật bù.',
    'answer.sync.failed':'Lần đồng bộ gần nhất có vẻ đã lỗi và tôi chưa có ghi nhận lấy dữ liệu thành công. Nếu tình trạng tiếp diễn, bạn có thể cần kết nối lại WHOOP.',
    'answer.sync.never':'Tôi chưa có ghi nhận đồng bộ nào nên chưa thể xác nhận việc đồng bộ từng thành công.',
    'answer.sync.incomplete':'Tôi chỉ xác nhận được một phần trạng thái đồng bộ. Ghi nhận chưa đầy đủ nên chưa thể xác định kết quả gần nhất.',
  },
});
