export const COMMAND_EXTRA_CATALOG = Object.freeze({
  'zh-TW': {
    'bot.log.invalid':'⚠️ 這筆記錄有問題，尚未儲存。',
    'bot.log.unparsed':'⚠️ 看不懂「{input}」。\n\n用法例如：\n/log alcohol 3 drinks\n/log caffeine 2 coffee\n/log flight TPE SGN\n/log sick\n/log magnesium 300mg\n\n可用類別：{categories}',
    'bot.status.title':'🩺 系統狀態', 'bot.status.bot':'Bot：✅ 運作中',
    'bot.status.timezone':'時區：{timezone}', 'bot.status.data':'WHOOP 資料：{status}',
    'bot.status.dataPresent':'✅ {days} 天（{from} ～ {to}）', 'bot.status.notStarted':'尚未開始',
    'bot.status.authorization':'授權：{status}', 'bot.status.authorized':'✅ 已授權',
    'bot.status.unauthorized':'尚未授權', 'bot.status.missingScopes':'（缺 {scopes}）',
    'bot.status.backfill':'Backfill：{status}', 'bot.status.complete':'✅ 完成',
    'bot.status.inProgress':'進行中', 'bot.status.lastSync':'最後同步：{value}',
    'bot.status.neverSynced':'尚未同步', 'bot.status.probe':'Capability probe：{status}',
    'bot.status.probed':'✅ 已執行', 'bot.status.notProbed':'尚未執行',
    'bot.status.predictionReady':'預測就緒：✅ 可訓練',
    'bot.status.predictionUnready':'預測就緒：尚未（{usable}/{required} 筆可用樣本）',
    'bot.status.insights':'長期規律：{count} 項', 'bot.status.noInsights':'長期規律：尚未形成',
    'bot.status.journal':'Journal：{count} 筆',
    'bot.status.proactiveTitle':'🔔 Proactive Agent',
    'bot.status.stage.STAGE_0':'尚未開始累積資料',
    'bot.status.stage.STAGE_1':'累積中，還不足以主動分析',
    'bot.status.stage.STAGE_2':'資料有限，主動分析尚未啟用',
    'bot.status.stage.STAGE_3':'✅ 已啟用',
    'bot.status.stage.STAGE_4':'✅ 已啟用（已有長期規律）',
    'bot.status.proactiveState':'狀態：{state}', 'bot.status.pendingYes':'待回答問題：有（{factor}）',
    'bot.status.pendingNo':'待回答問題：無', 'bot.status.lastAction':'最近一次動作：{date} {action}',
    'bot.status.noAction':'最近一次動作：尚無',
    'bot.status.action.IGNORE':'略過', 'bot.status.action.LOG_ONLY':'只記錄',
    'bot.status.action.ASK_CONTEXT':'詢問脈絡', 'bot.status.action.NOTIFY':'已通知',
    'bot.status.action.FOLLOW_UP':'後續追蹤', 'bot.status.action.UNKNOWN':'已處理',
    'bot.prediction.title':'🔮 恢復預測', 'bot.prediction.state':'狀態：{state}',
    'bot.prediction.state.READY':'可訓練', 'bot.prediction.state.DEGRADED':'資料不適合建立模型',
    'bot.prediction.state.INSUFFICIENT_DATA':'資料不足',
    'bot.prediction.state.NO_DATA':'尚無資料',
    'bot.prediction.state.WARMING_UP':'資料累積中',
    'bot.prediction.state.LIMITED':'資料有限',
    'bot.prediction.state.UNAVAILABLE':'不可用',
    'bot.prediction.usable':'目前可用樣本：{count} 筆',
    'bot.prediction.required':'最低需求：{count} 筆',
    'bot.prediction.degraded':'樣本數雖然夠了，但目前的資料結構算不出可用的模型，所以我不會給你任何預測數字。',
    'bot.prediction.insufficient':'資料量還不足以訓練預測模型，所以我不會給你任何預測數字。',
    'bot.prediction.caveat':'（一個沒有足夠資料支撐的預測，比沒有預測更糟。）',
    'bot.prediction.dataReady':'資料就緒：✅ 可訓練', 'bot.prediction.modelUntrained':'模型狀態：尚未訓練（下一次排程執行時會訓練）',
    'bot.prediction.modelState':'模型狀態：{state}',
    'bot.prediction.maturity.NO_DATA':'尚無資料',
    'bot.prediction.maturity.INSUFFICIENT_DATA':'資料累積中',
    'bot.prediction.maturity.MODEL_UNAVAILABLE':'目前的資料結構算不出模型',
    'bot.prediction.maturity.TRAINABLE':'已訓練，但還沒有足夠的測試資料可以評估',
    'bot.prediction.maturity.EVALUATED_UNQUALIFIED':'已評估，但還沒達到可發布的標準',
    'bot.prediction.maturity.QUALIFIED':'✅ 已通過品質門檻',
    'bot.prediction.maturity.STALE':'模型已過期，需要重新訓練',
    'bot.prediction.maturity.UNSUPPORTED':'這個帳號拿不到所需的欄位',
    'bot.prediction.testSamples':'  測試樣本 {count} 筆（時序切分，不含未來資料）',
    'bot.prediction.baselineBetter':'✅ 優於', 'bot.prediction.baselineWorse':'❌ 沒有優於',
    'bot.prediction.baseline':'  對照「只用歷史平均猜」：{verdict}（基準 MAE {value}）',
    'bot.prediction.qualified':'這個模型已通過品質門檻。',
    'bot.prediction.unqualified':'目前不會給你預測數字。模型還沒有被證明夠準；在證明之前給出一個數字只會誤導你。',
    'bot.prediction.scorecard':'過往預測準確度：',
    'bot.prediction.evaluated':'  已評估 {count} 次',
    'bot.prediction.coverage':'  區間涵蓋率 {value}%',
  },
  en: {
    'bot.log.invalid':'⚠️ This entry is invalid and was not saved.',
    'bot.log.unparsed':'⚠️ I could not understand “{input}.”\n\nFor example:\n/log alcohol 3 drinks\n/log caffeine 2 coffee\n/log flight TPE SGN\n/log sick\n/log magnesium 300mg\n\nCategories: {categories}',
    'bot.status.title':'🩺 Service status', 'bot.status.bot':'Bot: ✅ running',
    'bot.status.timezone':'Timezone: {timezone}', 'bot.status.data':'WHOOP data: {status}',
    'bot.status.dataPresent':'✅ {days} days ({from}–{to})', 'bot.status.notStarted':'not started',
    'bot.status.authorization':'Authorization: {status}', 'bot.status.authorized':'✅ authorized',
    'bot.status.unauthorized':'not authorized', 'bot.status.missingScopes':' (missing {scopes})',
    'bot.status.backfill':'Backfill: {status}', 'bot.status.complete':'✅ complete',
    'bot.status.inProgress':'in progress', 'bot.status.lastSync':'Last sync: {value}',
    'bot.status.neverSynced':'never synced', 'bot.status.probe':'Capability check: {status}',
    'bot.status.probed':'✅ complete', 'bot.status.notProbed':'not run',
    'bot.status.predictionReady':'Prediction data: ✅ trainable',
    'bot.status.predictionUnready':'Prediction data: not ready ({usable}/{required} usable samples)',
    'bot.status.insights':'Longer-term patterns: {count}', 'bot.status.noInsights':'Longer-term patterns: none yet',
    'bot.status.journal':'Journal: {count} entries',
    'bot.status.proactiveTitle':'🔔 Proactive monitoring',
    'bot.status.stage.STAGE_0':'no data yet',
    'bot.status.stage.STAGE_1':'building history; too little for proactive analysis',
    'bot.status.stage.STAGE_2':'limited data; proactive analysis is not active',
    'bot.status.stage.STAGE_3':'✅ active',
    'bot.status.stage.STAGE_4':'✅ active, with longer-term patterns',
    'bot.status.proactiveState':'Status: {state}', 'bot.status.pendingYes':'Pending question: yes ({factor})',
    'bot.status.pendingNo':'Pending question: none', 'bot.status.lastAction':'Last action: {date} {action}',
    'bot.status.noAction':'Last action: none',
    'bot.status.action.IGNORE':'skipped', 'bot.status.action.LOG_ONLY':'recorded without a message',
    'bot.status.action.ASK_CONTEXT':'asked for context', 'bot.status.action.NOTIFY':'sent a notice',
    'bot.status.action.FOLLOW_UP':'followed up', 'bot.status.action.UNKNOWN':'processed',
    'bot.prediction.title':'🔮 Recovery prediction', 'bot.prediction.state':'Status: {state}',
    'bot.prediction.state.READY':'trainable', 'bot.prediction.state.DEGRADED':'data unsuitable for a model',
    'bot.prediction.state.INSUFFICIENT_DATA':'insufficient data',
    'bot.prediction.state.NO_DATA':'no data',
    'bot.prediction.state.WARMING_UP':'building history',
    'bot.prediction.state.LIMITED':'limited data',
    'bot.prediction.state.UNAVAILABLE':'unavailable',
    'bot.prediction.usable':'Usable samples: {count}',
    'bot.prediction.required':'Minimum needed: {count}',
    'bot.prediction.degraded':'There are enough samples, but the data structure cannot support a usable model. I will not give a prediction number.',
    'bot.prediction.insufficient':'There is not enough data to train a prediction model. I will not give a prediction number.',
    'bot.prediction.caveat':'A prediction without enough supporting data would mislead you.',
    'bot.prediction.dataReady':'Data readiness: ✅ trainable', 'bot.prediction.modelUntrained':'Model: not trained yet (training is scheduled)',
    'bot.prediction.modelState':'Model: {state}',
    'bot.prediction.maturity.NO_DATA':'no data',
    'bot.prediction.maturity.INSUFFICIENT_DATA':'building history',
    'bot.prediction.maturity.MODEL_UNAVAILABLE':'no usable model can be built from current data',
    'bot.prediction.maturity.TRAINABLE':'trained, but too few test samples to evaluate',
    'bot.prediction.maturity.EVALUATED_UNQUALIFIED':'evaluated, but below publication quality',
    'bot.prediction.maturity.QUALIFIED':'✅ quality threshold met',
    'bot.prediction.maturity.STALE':'model expired and needs retraining',
    'bot.prediction.maturity.UNSUPPORTED':'required fields are unavailable for this account',
    'bot.prediction.testSamples':'  Test samples: {count} (chronological split; no future data)',
    'bot.prediction.baselineBetter':'✅ better', 'bot.prediction.baselineWorse':'❌ not better',
    'bot.prediction.baseline':'  Compared with a historical-mean baseline: {verdict} (baseline MAE {value})',
    'bot.prediction.qualified':'This model has met the quality threshold.',
    'bot.prediction.unqualified':'I will not show a prediction number yet. The model has not been shown to be accurate enough.',
    'bot.prediction.scorecard':'Past prediction accuracy:',
    'bot.prediction.evaluated':'  Evaluated {count} times',
    'bot.prediction.coverage':'  Interval coverage: {value}%',
  },
  vi: {
    'bot.log.invalid':'⚠️ Ghi chép này không hợp lệ và chưa được lưu.',
    'bot.log.unparsed':'⚠️ Tôi chưa hiểu “{input}”.\n\nVí dụ:\n/log alcohol 3 drinks\n/log caffeine 2 coffee\n/log flight TPE SGN\n/log sick\n/log magnesium 300mg\n\nDanh mục: {categories}',
    'bot.status.title':'🩺 Trạng thái hệ thống', 'bot.status.bot':'Bot: ✅ đang hoạt động',
    'bot.status.timezone':'Múi giờ: {timezone}', 'bot.status.data':'Dữ liệu WHOOP: {status}',
    'bot.status.dataPresent':'✅ {days} ngày ({from}–{to})', 'bot.status.notStarted':'chưa bắt đầu',
    'bot.status.authorization':'Quyền truy cập: {status}', 'bot.status.authorized':'✅ đã cấp',
    'bot.status.unauthorized':'chưa cấp', 'bot.status.missingScopes':' (thiếu {scopes})',
    'bot.status.backfill':'Đồng bộ lịch sử: {status}', 'bot.status.complete':'✅ hoàn tất',
    'bot.status.inProgress':'đang thực hiện', 'bot.status.lastSync':'Lần đồng bộ cuối: {value}',
    'bot.status.neverSynced':'chưa đồng bộ', 'bot.status.probe':'Kiểm tra khả năng truy cập: {status}',
    'bot.status.probed':'✅ hoàn tất', 'bot.status.notProbed':'chưa chạy',
    'bot.status.predictionReady':'Dữ liệu dự đoán: ✅ có thể huấn luyện',
    'bot.status.predictionUnready':'Dữ liệu dự đoán: chưa sẵn sàng ({usable}/{required} mẫu dùng được)',
    'bot.status.insights':'Quy luật dài hạn: {count}', 'bot.status.noInsights':'Quy luật dài hạn: chưa có',
    'bot.status.journal':'Journal: {count} ghi chép',
    'bot.status.proactiveTitle':'🔔 Theo dõi chủ động',
    'bot.status.stage.STAGE_0':'chưa có dữ liệu',
    'bot.status.stage.STAGE_1':'đang tích lũy; chưa đủ để phân tích chủ động',
    'bot.status.stage.STAGE_2':'dữ liệu còn hạn chế; phân tích chủ động chưa hoạt động',
    'bot.status.stage.STAGE_3':'✅ đang hoạt động',
    'bot.status.stage.STAGE_4':'✅ đang hoạt động, đã có quy luật dài hạn',
    'bot.status.proactiveState':'Trạng thái: {state}', 'bot.status.pendingYes':'Câu hỏi đang chờ trả lời: có ({factor})',
    'bot.status.pendingNo':'Câu hỏi đang chờ trả lời: không có', 'bot.status.lastAction':'Hành động gần nhất: {date} {action}',
    'bot.status.noAction':'Hành động gần nhất: chưa có',
    'bot.status.action.IGNORE':'đã bỏ qua', 'bot.status.action.LOG_ONLY':'chỉ ghi nhận',
    'bot.status.action.ASK_CONTEXT':'đã hỏi thêm bối cảnh', 'bot.status.action.NOTIFY':'đã thông báo',
    'bot.status.action.FOLLOW_UP':'đã theo dõi tiếp', 'bot.status.action.UNKNOWN':'đã xử lý',
    'bot.prediction.title':'🔮 Dự đoán Phục hồi', 'bot.prediction.state':'Trạng thái: {state}',
    'bot.prediction.state.READY':'có thể huấn luyện', 'bot.prediction.state.DEGRADED':'dữ liệu không phù hợp để tạo mô hình',
    'bot.prediction.state.INSUFFICIENT_DATA':'chưa đủ dữ liệu',
    'bot.prediction.state.NO_DATA':'chưa có dữ liệu',
    'bot.prediction.state.WARMING_UP':'đang tích lũy lịch sử',
    'bot.prediction.state.LIMITED':'dữ liệu còn hạn chế',
    'bot.prediction.state.UNAVAILABLE':'không khả dụng',
    'bot.prediction.usable':'Mẫu dùng được: {count}',
    'bot.prediction.required':'Tối thiểu cần: {count}',
    'bot.prediction.degraded':'Đã đủ số mẫu nhưng cấu trúc dữ liệu chưa tạo được mô hình dùng được. Tôi sẽ không đưa ra con số dự đoán.',
    'bot.prediction.insufficient':'Chưa đủ dữ liệu để huấn luyện mô hình dự đoán. Tôi sẽ không đưa ra con số dự đoán.',
    'bot.prediction.caveat':'Dự đoán không có đủ dữ liệu hỗ trợ có thể gây hiểu nhầm.',
    'bot.prediction.dataReady':'Dữ liệu: ✅ có thể huấn luyện', 'bot.prediction.modelUntrained':'Mô hình: chưa huấn luyện (đã lên lịch huấn luyện)',
    'bot.prediction.modelState':'Mô hình: {state}',
    'bot.prediction.maturity.NO_DATA':'chưa có dữ liệu',
    'bot.prediction.maturity.INSUFFICIENT_DATA':'đang tích lũy lịch sử',
    'bot.prediction.maturity.MODEL_UNAVAILABLE':'dữ liệu hiện tại chưa tạo được mô hình dùng được',
    'bot.prediction.maturity.TRAINABLE':'đã huấn luyện nhưng quá ít mẫu kiểm tra để đánh giá',
    'bot.prediction.maturity.EVALUATED_UNQUALIFIED':'đã đánh giá nhưng chưa đạt chuẩn công bố',
    'bot.prediction.maturity.QUALIFIED':'✅ đạt ngưỡng chất lượng',
    'bot.prediction.maturity.STALE':'mô hình đã cũ và cần huấn luyện lại',
    'bot.prediction.maturity.UNSUPPORTED':'tài khoản này không có các trường dữ liệu cần thiết',
    'bot.prediction.testSamples':'  Mẫu kiểm tra: {count} (chia theo thời gian; không dùng dữ liệu tương lai)',
    'bot.prediction.baselineBetter':'✅ tốt hơn', 'bot.prediction.baselineWorse':'❌ không tốt hơn',
    'bot.prediction.baseline':'  So với mức cơ sở là trung bình lịch sử: {verdict} (MAE cơ sở {value})',
    'bot.prediction.qualified':'Mô hình này đã đạt ngưỡng chất lượng.',
    'bot.prediction.unqualified':'Tôi chưa hiển thị con số dự đoán. Độ chính xác của mô hình chưa được chứng minh đủ tốt.',
    'bot.prediction.scorecard':'Độ chính xác các dự đoán trước:',
    'bot.prediction.evaluated':'  Đã đánh giá {count} lần',
    'bot.prediction.coverage':'  Tỷ lệ bao phủ khoảng dự đoán: {value}%',
  },
});
