/** Existing bot command copy. Values are presentation only. */
export const COMMAND_CATALOG = Object.freeze({
  'zh-TW': {
    'bot.help.title':'🤖 我可以做這些事',
    'bot.help.now':'【現在就能用】',
    'bot.help.log':'/log — 記錄事件，例如 /log alcohol 3 drinks',
    'bot.help.logNatural':'       也可以直接講「昨天喝了三杯酒」「今天飛胡志明」',
    'bot.help.journal':'/journal — 看最近的記錄（/journal 7、/journal 30）',
    'bot.help.healthdata':'/healthdata — 資料同步與涵蓋狀況',
    'bot.help.status':'/status — 系統整體狀態',
    'bot.help.cost':'/cost — AI 使用成本',
    'bot.help.experiment':'/experiment — 建立與追蹤自我實驗',
    'bot.help.help':'/help — 這則說明',
    'bot.help.questions':'【健康問答】直接用中文問我：',
    'bot.help.q1':'· 我今天狀態怎樣？', 'bot.help.q2':'· 最近 HRV 如何？',
    'bot.help.q3':'· 最近睡眠有沒有變差？', 'bot.help.q4':'· 最近 30 天最好是哪一天？',
    'bot.help.q5':'· 今天最值得注意的是什麼？',
    'bot.help.noData':'【還不能用（等 WHOOP 資料）】',
    'bot.help.noQa':'· 健康問答 —— 目前沒有任何生理資料可以分析',
    'bot.help.longTerm':'【長期分析】',
    'bot.help.insights':'/insights — 長期規律{suffix}',
    'bot.help.insightsCount':'（目前 {count} 項）', 'bot.help.insightsEmpty':'（目前尚未形成）',
    'bot.help.predictions':'/predictions — 恢復預測{suffix}',
    'bot.help.predictionsUnready':'（資料量還不足）',
    'bot.help.healthspan':'/healthspan — 長期生理盤點（目前只盤點資料，不給分數）',
    'bot.help.evidence':'/evidence — 目前結論背後的證據與樣本數',
    'bot.start.title':'👋 WHOOP 健康助理已啟動。',
    'bot.start.noData':'目前還沒有同步到任何健康資料。',
    'bot.start.wait':'等手錶開始產生資料、並完成 WHOOP 授權之後，我會自動開始分析 —— 你不需要再做任何設定。',
    'bot.start.available':'在那之前你已經可以用的功能：',
    'bot.start.log':'· /log 記錄喝酒、咖啡、生病、旅行等事件（會完整保存，之後可以拿來對照）',
    'bot.start.healthdata':'· /healthdata 看目前的資料狀態',
    'bot.start.help':'· /help 看完整說明',
    'bot.start.data':'目前有 {days} 天睡眠資料（{from} ～ {to}）。',
    'bot.start.ask':'直接問我問題就好，例如「我今天狀態怎樣？」。/help 看更多。',
    'bot.journal.empty':'目前沒有 Journal 紀錄。\n\n（最近 {days} 天內）用 /log 開始記錄，例如 /log alcohol 3 drinks',
    'bot.journal.title':'📓 最近 {days} 天的記錄（{count} 筆）',
    'bot.journal.entry':'  · {category}{subtype}{amount}',
    'bot.insights.title':'🧠 長期規律',
    'bot.insights.empty':'目前資料還不足以形成長期規律。\n\n要看出「什麼會影響你的恢復」，需要累積一段時間的 WHOOP 資料，再加上 /log 記錄的生活事件當對照。',
    'bot.insights.line':'「{factor}」與隔天{metric}目前呈現{direction}關聯（r={effect}，樣本 {count} 天）。{status}',
    'bot.insights.directionPositive':'正向', 'bot.insights.directionNegative':'負向', 'bot.insights.directionUnknown':'尚不明顯',
    'bot.insights.status.SUPPORTED':'這項觀察已有重複支持。',
    'bot.insights.status.EMERGING':'這項觀察仍在確認中。',
    'bot.insights.status.HYPOTHESIS':'這只是初步假設。',
    'bot.insights.status.RETIRED':'已被較新的版本取代',
    'bot.insights.meta':'   樣本 {count}，v{version}',
    'bot.insights.history':'   ↳ v{version}（{status}）{statement}',
    'bot.insights.unavailable':'部分舊觀察目前無法以這個語言安全呈現。',
    'bot.insights.note':'註：全部都是個人層級觀察到的關聯，不是因果關係。',
    'bot.insights.historyHint':'用 /insights history 可以看修正過程。',
  },
  en: {
    'bot.help.title':'🤖 Here is what I can do',
    'bot.help.now':'【Available now】',
    'bot.help.log':'/log — Record an event, such as /log alcohol 3 drinks',
    'bot.help.logNatural':'       You can also describe an event in your own words.',
    'bot.help.journal':'/journal — See recent entries (/journal 7 or /journal 30)',
    'bot.help.healthdata':'/healthdata — Sync and data coverage',
    'bot.help.status':'/status — Overall service status',
    'bot.help.cost':'/cost — AI usage cost',
    'bot.help.experiment':'/experiment — Create and track a self experiment',
    'bot.help.help':'/help — This guide',
    'bot.help.questions':'【Health questions】 Ask me directly:',
    'bot.help.q1':'· How am I doing today?', 'bot.help.q2':'· How has my HRV been lately?',
    'bot.help.q3':'· Has my sleep been getting worse?', 'bot.help.q4':'· What was my best day in the past 30 days?',
    'bot.help.q5':'· What changed most today?',
    'bot.help.noData':'【Available after WHOOP data arrives】',
    'bot.help.noQa':'· Health questions — there is no health data to analyze yet',
    'bot.help.longTerm':'【Longer-term analysis】',
    'bot.help.insights':'/insights — Longer-term patterns{suffix}',
    'bot.help.insightsCount':' ({count} so far)', 'bot.help.insightsEmpty':' (none yet)',
    'bot.help.predictions':'/predictions — Recovery prediction{suffix}',
    'bot.help.predictionsUnready':' (more data needed)',
    'bot.help.healthspan':'/healthspan — Longer-term health data overview (no score)',
    'bot.help.evidence':'/evidence — Evidence and sample sizes behind current conclusions',
    'bot.start.title':'👋 Your WHOOP health assistant is ready.',
    'bot.start.noData':'No health data has synced yet.',
    'bot.start.wait':'Once WHOOP has data and you have authorized access, I will start analyzing it automatically. There is nothing else to set up.',
    'bot.start.available':'You can already use:',
    'bot.start.log':'· /log to record alcohol, caffeine, illness, travel, and other events for later comparison',
    'bot.start.healthdata':'· /healthdata to check your data status',
    'bot.start.help':'· /help for the full guide',
    'bot.start.data':'I have {days} days of sleep data ({from}–{to}).',
    'bot.start.ask':'You can ask a question, such as “How am I doing today?” Use /help for more.',
    'bot.journal.empty':'There are no Journal entries from the past {days} days. Use /log to start, for example /log alcohol 3 drinks.',
    'bot.journal.title':'📓 Entries from the past {days} days ({count})',
    'bot.journal.entry':'  · {category}{subtype}{amount}',
    'bot.insights.title':'🧠 Longer-term patterns',
    'bot.insights.empty':'There is not enough data yet to identify longer-term patterns. WHOOP history and events recorded with /log provide the comparisons needed.',
    'bot.insights.line':'{factor} and next-day {metric} currently show a {direction} association (r={effect}, {count} days). {status}',
    'bot.insights.directionPositive':'positive', 'bot.insights.directionNegative':'negative', 'bot.insights.directionUnknown':'not yet clear',
    'bot.insights.status.SUPPORTED':'This observation has repeated support.',
    'bot.insights.status.EMERGING':'This observation is still being checked.',
    'bot.insights.status.HYPOTHESIS':'This is only a preliminary hypothesis.',
    'bot.insights.status.RETIRED':'Superseded by a newer revision',
    'bot.insights.meta':'   Sample: {count}, v{version}',
    'bot.insights.history':'   ↳ v{version} ({status}) {statement}',
    'bot.insights.unavailable':'Some older observations cannot yet be presented safely in this language.',
    'bot.insights.note':'These are personal observed associations, not proof of cause.',
    'bot.insights.historyHint':'Use /insights history to see earlier revisions.',
  },
  vi: {
    'bot.help.title':'🤖 Tôi có thể giúp bạn những việc sau',
    'bot.help.now':'【Có thể dùng ngay】',
    'bot.help.log':'/log — Ghi lại sự kiện, ví dụ /log alcohol 3 drinks',
    'bot.help.logNatural':'       Bạn cũng có thể mô tả sự kiện bằng lời của mình.',
    'bot.help.journal':'/journal — Xem các ghi chép gần đây (/journal 7 hoặc /journal 30)',
    'bot.help.healthdata':'/healthdata — Tình trạng đồng bộ và dữ liệu',
    'bot.help.status':'/status — Trạng thái chung của hệ thống',
    'bot.help.cost':'/cost — Chi phí sử dụng AI',
    'bot.help.experiment':'/experiment — Tạo và theo dõi thử nghiệm cá nhân',
    'bot.help.help':'/help — Hướng dẫn này',
    'bot.help.questions':'【Câu hỏi sức khỏe】 Bạn có thể hỏi trực tiếp:',
    'bot.help.q1':'· Hôm nay tình trạng của tôi thế nào?', 'bot.help.q2':'· HRV của tôi gần đây thế nào?',
    'bot.help.q3':'· Giấc ngủ của tôi có kém đi không?', 'bot.help.q4':'· Ngày tốt nhất trong 30 ngày qua là ngày nào?',
    'bot.help.q5':'· Hôm nay có thay đổi nào đáng chú ý nhất?',
    'bot.help.noData':'【Dùng được khi có dữ liệu WHOOP】',
    'bot.help.noQa':'· Câu hỏi sức khỏe — hiện chưa có dữ liệu để phân tích',
    'bot.help.longTerm':'【Phân tích dài hạn】',
    'bot.help.insights':'/insights — Các quy luật dài hạn{suffix}',
    'bot.help.insightsCount':' (hiện có {count})', 'bot.help.insightsEmpty':' (chưa có)',
    'bot.help.predictions':'/predictions — Dự đoán phục hồi{suffix}',
    'bot.help.predictionsUnready':' (cần thêm dữ liệu)',
    'bot.help.healthspan':'/healthspan — Tổng quan dữ liệu sức khỏe dài hạn (không chấm điểm)',
    'bot.help.evidence':'/evidence — Bằng chứng và cỡ mẫu đằng sau các kết luận hiện tại',
    'bot.start.title':'👋 Trợ lý sức khỏe WHOOP của bạn đã sẵn sàng.',
    'bot.start.noData':'Chưa có dữ liệu sức khỏe nào được đồng bộ.',
    'bot.start.wait':'Khi WHOOP có dữ liệu và bạn đã cấp quyền, tôi sẽ tự động bắt đầu phân tích. Bạn không cần thiết lập thêm.',
    'bot.start.available':'Bạn đã có thể dùng:',
    'bot.start.log':'· /log để ghi lại rượu bia, caffeine, bệnh, chuyến đi và các sự kiện khác để đối chiếu sau',
    'bot.start.healthdata':'· /healthdata để xem trạng thái dữ liệu',
    'bot.start.help':'· /help để xem hướng dẫn đầy đủ',
    'bot.start.data':'Tôi có {days} ngày dữ liệu giấc ngủ ({from}–{to}).',
    'bot.start.ask':'Bạn có thể hỏi, ví dụ “Hôm nay tình trạng của tôi thế nào?” Dùng /help để xem thêm.',
    'bot.journal.empty':'Không có ghi chép Journal nào trong {days} ngày qua. Dùng /log để bắt đầu, ví dụ /log alcohol 3 drinks.',
    'bot.journal.title':'📓 Ghi chép trong {days} ngày qua ({count} mục)',
    'bot.journal.entry':'  · {category}{subtype}{amount}',
    'bot.insights.title':'🧠 Các quy luật dài hạn',
    'bot.insights.empty':'Hiện chưa đủ dữ liệu để nhận ra các quy luật dài hạn. Lịch sử WHOOP và các sự kiện ghi bằng /log sẽ giúp tạo dữ liệu đối chiếu.',
    'bot.insights.line':'{factor} và {metric} ngày hôm sau hiện cho thấy mối liên hệ {direction} (r={effect}, {count} ngày). {status}',
    'bot.insights.directionPositive':'cùng chiều', 'bot.insights.directionNegative':'ngược chiều', 'bot.insights.directionUnknown':'chưa rõ',
    'bot.insights.status.SUPPORTED':'Nhận xét này đã được dữ liệu nhiều lần hỗ trợ.',
    'bot.insights.status.EMERGING':'Nhận xét này vẫn đang được kiểm tra.',
    'bot.insights.status.HYPOTHESIS':'Đây mới chỉ là giả thuyết ban đầu.',
    'bot.insights.status.RETIRED':'Đã được thay thế bằng phiên bản mới hơn',
    'bot.insights.meta':'   Cỡ mẫu: {count}, v{version}',
    'bot.insights.history':'   ↳ v{version} ({status}) {statement}',
    'bot.insights.unavailable':'Một số nhận xét cũ hiện chưa thể trình bày an toàn bằng ngôn ngữ này.',
    'bot.insights.note':'Đây là những mối liên hệ quan sát ở cấp độ cá nhân, không phải bằng chứng về nguyên nhân.',
    'bot.insights.historyHint':'Dùng /insights history để xem các lần chỉnh sửa trước.',
  },
});
