/** Approved general education claims, rendered without personal WHOOP data. */
export const EDUCATION_CATALOG = Object.freeze({
  'zh-TW': {
    'education.alcohol.tired':'酒精可能讓人短時間覺得疲倦。有些人會覺得比較快睡著，但後半夜的睡眠可能被打斷，也可能因為水分流失而讓隔天精神變差。',
    'education.alcohol.sleep':'酒精可能影響睡眠。常見的描述是入睡變快，但後半夜比較容易醒來、深睡與 REM 可能減少，整體感受到的睡眠品質因此下降。',
    'education.alcohol.hrv':'飲酒之後 HRV 偏低、靜息心率偏高是常見的觀察。一般認為與自律神經活動的變化有關，但影響程度因人、因量而異。',
    'education.alcohol.recovery':'飲酒之後恢復分數偏低是常見的觀察。不過恢復分數會受到多種因素影響，單靠這一項無法判定原因。',
    'education.late_sleep.tired':'熬夜之後沒精神很常見。睡眠時間被壓縮可能累積睡眠不足，作息往後移也可能讓白天的清醒程度下降。',
    'education.late_sleep.sleep':'晚睡可能讓可用的睡眠時間變短，睡眠階段的分佈也可能改變。',
    'education.late_sleep.hrv':'睡眠不足之後 HRV 偏低是常見的觀察，常被當成身體還在恢復的間接訊號之一。',
    'education.late_sleep.recovery':'睡得太少之後恢復分數偏低是常見的觀察。恢復分數會受到多種因素影響，不會只反映其中一項。',
    'education.short_sleep.tired':'睡得太少之後覺得累很常見，專注與精神都可能受影響。',
    'education.short_sleep.sleep':'睡眠時間不足時，各個睡眠階段的比例可能改變，不同人的樣子不太一樣。',
    'education.short_sleep.hrv':'睡眠不足之後 HRV 偏低是常見的觀察。',
    'education.short_sleep.recovery':'睡太少之後恢復分數偏低是常見的觀察，但實際影響多少因人而異。',
    'education.exercise.tired':'運動完覺得累很常見。可能與肌肉疲勞、能量消耗、水分與電解質流失，或這次強度比平常高有關。一般休息與補充之後會慢慢緩解。',
    'education.exercise.sleep':'規律運動常被認為對睡眠有幫助，但太接近睡前的高強度運動，有些人反而會比較難入睡。',
    'education.exercise.hrv':'強度較高的訓練後 HRV 可能暫時偏低，多數情況下休息之後會回升，不過每個人的恢復速度差很多。',
    'education.exercise.recovery':'高強度訓練的隔天恢復分數偏低是常見的觀察，通常與身體還在修復有關。',
    'education.stress.tired':'壓力可能讓人覺得疲倦。長時間的緊繃可能影響睡眠品質，也可能讓身體處在比較耗能的狀態。',
    'education.stress.sleep':'壓力常見的影響是比較難入睡、睡得比較淺，或半夜醒來。',
    'education.stress.hrv':'壓力可能讓 HRV 改變，常見的方向是偏低。HRV 常被當成自律神經活動的間接指標之一，但單一數字無法代表壓力大小。',
    'education.stress.recovery':'壓力大的時候恢復分數偏低並不少見。',
    'education.caffeine.tired':'咖啡因作用退去之後覺得疲倦很常見；它也可能因為影響了睡眠而讓隔天更累。',
    'education.caffeine.sleep':'咖啡因在體內代謝需要時間，下午之後攝取有些人會覺得入睡變慢、睡得比較淺。',
    'education.caffeine.hrv':'咖啡因可能讓心率上升、HRV 偏低，不過個別差異很大。',
    'education.caffeine.recovery':'咖啡因若影響了睡眠，恢復分數也可能跟著受影響。',
    'education.sickness.tired':'生病或感染期間覺得疲倦很常見，一般認為與免疫反應有關。',
    'education.sickness.sleep':'生病時睡眠常常變得比較破碎。',
    'education.sickness.hrv':'生病期間 HRV 偏低、靜息心率偏高是常見的觀察。',
    'education.sickness.recovery':'生病時恢復分數偏低很常見。',
    'education.thirdParty':'不過只憑這句話沒辦法判斷他的狀況或原因，我這邊也看不到他的量測資料。',
    'education.thirdPartySevere':'你描述的狀況已經超過一般的疲倦 —— 如果他現在有呼吸困難、胸痛、意識不清、持續嘔吐或叫不醒，請立刻尋求緊急醫療協助，不要等他自己好。',
    'education.thirdPartyMild':'如果只是輕微疲倦，先休息、補充水分並觀察就好；但若出現呼吸困難、胸痛、意識不清、持續嘔吐或叫不醒，應該立刻尋求緊急協助。',
    'education.general':'每個人的差異很大，所以這只是一般情況，不見得會發生在每個人身上。',
  },
  en: {
    'education.alcohol.tired':'Alcohol may cause short-term tiredness. Some people fall asleep faster, but sleep later in the night may be disrupted, and fluid loss may leave them less alert the next day.',
    'education.alcohol.sleep':'Alcohol may affect sleep. People may fall asleep faster but wake more often later; deep and REM sleep may decrease, reducing perceived sleep quality.',
    'education.alcohol.hrv':'Lower HRV and higher resting heart rate after drinking are commonly observed. Changes in autonomic activity may contribute, but the effect varies by person and amount consumed.',
    'education.alcohol.recovery':'A lower Recovery score after drinking is commonly observed. Many factors affect Recovery, so that score alone cannot identify a cause.',
    'education.late_sleep.tired':'Feeling less alert after a late night is common. Shorter sleep can add to sleep loss, and a later schedule may reduce daytime alertness.',
    'education.late_sleep.sleep':'A later bedtime may shorten the time available for sleep and may change how sleep stages are distributed.',
    'education.late_sleep.hrv':'Lower HRV after insufficient sleep is commonly observed and may be an indirect sign that the body is still recovering.',
    'education.late_sleep.recovery':'A lower Recovery score after too little sleep is commonly observed. Recovery reflects multiple factors, not just one.',
    'education.short_sleep.tired':'Tiredness after too little sleep is common; attention and alertness may also be affected.',
    'education.short_sleep.sleep':'When sleep is too short, the proportions of sleep stages may change, and the pattern differs between people.',
    'education.short_sleep.hrv':'Lower HRV after insufficient sleep is commonly observed.',
    'education.short_sleep.recovery':'A lower Recovery score after too little sleep is commonly observed, but the size of the effect varies.',
    'education.exercise.tired':'Feeling tired after exercise is common. Muscle fatigue, energy use, loss of fluids or electrolytes, or an unusually hard session may contribute. Rest and replenishment often help.',
    'education.exercise.sleep':'Regular exercise is often associated with better sleep, though intense exercise close to bedtime can make falling asleep harder for some people.',
    'education.exercise.hrv':'HRV may be temporarily lower after intense training and often rises with rest, though recovery time varies widely.',
    'education.exercise.recovery':'A lower Recovery score the day after hard training is commonly observed and may reflect ongoing physical recovery.',
    'education.stress.tired':'Stress may cause tiredness. Prolonged tension can affect sleep quality and may leave the body using more energy.',
    'education.stress.sleep':'Stress commonly makes it harder to fall asleep, leads to lighter sleep, or causes waking during the night.',
    'education.stress.hrv':'Stress may change HRV, often toward lower values. HRV can be an indirect sign of autonomic activity, but one number cannot measure how stressed someone is.',
    'education.stress.recovery':'A lower Recovery score during stressful periods is not uncommon.',
    'education.caffeine.tired':'Feeling tired as caffeine wears off is common. If caffeine disrupts sleep, it may also make the next day more tiring.',
    'education.caffeine.sleep':'Caffeine takes time to clear. After afternoon intake, some people take longer to fall asleep or sleep more lightly.',
    'education.caffeine.hrv':'Caffeine may raise heart rate and lower HRV, but individual responses vary greatly.',
    'education.caffeine.recovery':'If caffeine affects sleep, Recovery may also be affected.',
    'education.sickness.tired':'Tiredness during illness or infection is common and may be related to the immune response.',
    'education.sickness.sleep':'Sleep is often more fragmented during illness.',
    'education.sickness.hrv':'Lower HRV and higher resting heart rate during illness are commonly observed.',
    'education.sickness.recovery':'A lower Recovery score during illness is common.',
    'education.thirdParty':'I cannot determine that person’s condition or cause from this message, and I cannot see their measurements.',
    'education.thirdPartySevere':'What you describe goes beyond ordinary tiredness. If they have trouble breathing, chest pain, confusion, persistent vomiting, or cannot be awakened, seek emergency medical help now.',
    'education.thirdPartyMild':'For mild tiredness, rest, fluids, and observation may help. If trouble breathing, chest pain, confusion, persistent vomiting, or inability to wake them occurs, seek emergency help immediately.',
    'education.general':'People vary widely. These are general possibilities and may not apply to everyone.',
  },
  vi: {
    'education.alcohol.tired':'Rượu bia có thể gây mệt trong ngắn hạn. Một số người dễ ngủ hơn, nhưng giấc ngủ nửa sau đêm có thể bị gián đoạn; mất nước cũng có thể khiến hôm sau kém tỉnh táo.',
    'education.alcohol.sleep':'Rượu bia có thể ảnh hưởng giấc ngủ. Bạn có thể dễ ngủ hơn nhưng thức giấc nhiều hơn về sau; ngủ sâu và REM có thể giảm, khiến chất lượng giấc ngủ cảm nhận kém đi.',
    'education.alcohol.hrv':'HRV thấp hơn và nhịp tim lúc nghỉ cao hơn sau khi uống rượu bia là những quan sát thường gặp. Hoạt động thần kinh tự chủ có thể góp phần, nhưng mức ảnh hưởng tùy người và lượng uống.',
    'education.alcohol.recovery':'Điểm Phục hồi thấp hơn sau khi uống rượu bia là quan sát thường gặp. Nhiều yếu tố ảnh hưởng đến Phục hồi, nên riêng điểm này không xác định được nguyên nhân.',
    'education.late_sleep.tired':'Kém tỉnh táo sau khi thức khuya là điều thường gặp. Ngủ ngắn hơn có thể làm tích lũy thiếu ngủ; giờ ngủ muộn hơn cũng có thể giảm sự tỉnh táo ban ngày.',
    'education.late_sleep.sleep':'Đi ngủ muộn có thể rút ngắn thời gian dành cho giấc ngủ và thay đổi phân bố các giai đoạn ngủ.',
    'education.late_sleep.hrv':'HRV thấp hơn sau khi thiếu ngủ là quan sát thường gặp và có thể là dấu hiệu gián tiếp rằng cơ thể vẫn đang hồi phục.',
    'education.late_sleep.recovery':'Điểm Phục hồi thấp hơn sau khi ngủ quá ít là quan sát thường gặp. Phục hồi phản ánh nhiều yếu tố chứ không chỉ một yếu tố.',
    'education.short_sleep.tired':'Mệt sau khi ngủ quá ít là điều thường gặp; khả năng tập trung và tỉnh táo cũng có thể bị ảnh hưởng.',
    'education.short_sleep.sleep':'Khi ngủ không đủ, tỷ lệ các giai đoạn ngủ có thể thay đổi và khác nhau giữa từng người.',
    'education.short_sleep.hrv':'HRV thấp hơn sau khi thiếu ngủ là quan sát thường gặp.',
    'education.short_sleep.recovery':'Điểm Phục hồi thấp hơn sau khi ngủ quá ít là quan sát thường gặp, nhưng mức ảnh hưởng khác nhau giữa từng người.',
    'education.exercise.tired':'Mệt sau khi vận động là điều thường gặp. Mỏi cơ, tiêu hao năng lượng, mất nước hoặc điện giải, hay buổi tập nặng hơn thường lệ đều có thể góp phần. Nghỉ ngơi và bù lại thường giúp cải thiện.',
    'education.exercise.sleep':'Vận động đều đặn thường gắn với giấc ngủ tốt hơn, nhưng tập cường độ cao sát giờ ngủ có thể khiến một số người khó ngủ.',
    'education.exercise.hrv':'HRV có thể tạm thời thấp hơn sau buổi tập nặng và thường tăng lại khi nghỉ, nhưng tốc độ hồi phục khác nhau nhiều.',
    'education.exercise.recovery':'Điểm Phục hồi thấp hơn vào ngày sau buổi tập nặng là quan sát thường gặp và có thể phản ánh cơ thể vẫn đang hồi phục.',
    'education.stress.tired':'Căng thẳng có thể gây mệt. Căng kéo dài có thể ảnh hưởng chất lượng giấc ngủ và làm cơ thể tiêu hao nhiều năng lượng hơn.',
    'education.stress.sleep':'Căng thẳng thường khiến khó ngủ, ngủ nông hơn hoặc thức giấc giữa đêm.',
    'education.stress.hrv':'Căng thẳng có thể làm HRV thay đổi, thường theo hướng thấp hơn. HRV là một dấu hiệu gián tiếp về hoạt động thần kinh tự chủ, nhưng một con số không đo được mức căng thẳng.',
    'education.stress.recovery':'Điểm Phục hồi thấp hơn trong giai đoạn căng thẳng không phải hiếm gặp.',
    'education.caffeine.tired':'Cảm thấy mệt khi tác dụng caffeine hết là điều thường gặp. Nếu caffeine làm gián đoạn giấc ngủ, hôm sau bạn cũng có thể mệt hơn.',
    'education.caffeine.sleep':'Caffeine cần thời gian để được đào thải. Uống sau buổi chiều có thể khiến một số người khó ngủ hoặc ngủ nông hơn.',
    'education.caffeine.hrv':'Caffeine có thể làm nhịp tim tăng và HRV giảm, nhưng phản ứng mỗi người rất khác nhau.',
    'education.caffeine.recovery':'Nếu caffeine ảnh hưởng giấc ngủ, điểm Phục hồi cũng có thể bị ảnh hưởng.',
    'education.sickness.tired':'Mệt khi bị bệnh hoặc nhiễm trùng là điều thường gặp và có thể liên quan đến phản ứng miễn dịch.',
    'education.sickness.sleep':'Giấc ngủ thường bị gián đoạn nhiều hơn khi bị bệnh.',
    'education.sickness.hrv':'HRV thấp hơn và nhịp tim lúc nghỉ cao hơn khi bị bệnh là những quan sát thường gặp.',
    'education.sickness.recovery':'Điểm Phục hồi thấp hơn khi bị bệnh là điều thường gặp.',
    'education.thirdParty':'Tôi không thể xác định tình trạng hoặc nguyên nhân của người đó chỉ từ lời nhắn này, và tôi không thấy dữ liệu đo của họ.',
    'education.thirdPartySevere':'Điều bạn mô tả nghiêm trọng hơn mệt mỏi thông thường. Nếu họ khó thở, đau ngực, lú lẫn, nôn liên tục hoặc không thể đánh thức, hãy tìm trợ giúp cấp cứu ngay.',
    'education.thirdPartyMild':'Nếu chỉ mệt nhẹ, nghỉ ngơi, uống nước và theo dõi có thể giúp ích. Nếu xuất hiện khó thở, đau ngực, lú lẫn, nôn liên tục hoặc không thể đánh thức, hãy tìm trợ giúp cấp cứu ngay.',
    'education.general':'Mỗi người rất khác nhau. Đây chỉ là những khả năng chung và có thể không đúng với tất cả mọi người.',
  },
});
