export const EXPERIMENT_CATALOG = Object.freeze({
  'zh-TW': {
    'experiment.step.name':'這個實驗要叫什麼名字？（例如「睡前不喝咖啡」）',
    'experiment.step.hypothesis':'你的假設是什麼？（例如「深睡會變多」；沒有就回「跳過」）',
    'experiment.step.intervention':'具體要做什麼？（例如「14:00 後不攝取咖啡因」）',
    'experiment.step.target_metric':'要觀察哪個指標？（例如 深睡、恢復、HRV、睡眠效率）',
    'experiment.step.duration_days':'打算做幾天？（建議 14 天以上，直接回數字）',
    'experiment.begin':'🧪 來建立一個實驗。\n\n（{step}/{total}）{question}\n\n隨時輸入「取消」可以中止。',
    'experiment.cancel':'好，這個實驗先不建立了。',
    'experiment.metricInvalid':'我不認得「{input}」這個指標。\n可以用：恢復、HRV、靜息心率、睡眠、深睡、REM、睡眠效率、睡眠一致性、Strain。\n\n（{step}/{total}）{question}',
    'experiment.durationInvalid':'請給一個 3 到 180 之間的天數。\n\n（{step}/{total}）{question}',
    'experiment.next':'（{step}/{total}）{question}',
    'experiment.unnamed':'未命名實驗','experiment.createFailed':'目前無法建立實驗，請稍後再試。',
    'experiment.created':'✅ 實驗已建立並開始（#{id}）',
    'experiment.name':'名稱：{name}', 'experiment.hypothesis':'假設：{value}',
    'experiment.intervention':'做法：{value}','experiment.target':'觀察指標：{metric}',
    'experiment.period':'期間：{from} ～ {to}（{days} 天）',
    'experiment.baselinePeriod':'對照期：{from} ～ {to}',
    'experiment.finishHint':'結束後用 /experiment stop 收尾，我會做前後對照。',
    'experiment.caveat':'（提醒：這是 n=1 的個人前後比較，只能看出關聯，不能證明因果。）',
    'experiment.none':'目前沒有任何實驗。用 /experiment create 建立一個。',
    'experiment.listTitle':'🧪 實驗清單','experiment.listEntry':'#{id} {name}  [{status}]',
    'experiment.listMetric':'   指標：{metrics}','experiment.notSpecified':'未指定',
    'experiment.listPeriod':'   期間：{from} ～ {to}', 'experiment.inProgress':'進行中',
    'experiment.statusTitle':'🧪 #{id} {name}','experiment.status':'狀態：{status}',
    'experiment.status.RUNNING':'進行中','experiment.status.COMPLETED':'已完成',
    'experiment.status.CANCELLED':'已取消','experiment.status.UNKNOWN':'狀態不明',
    'experiment.status.DRAFT':'草稿','experiment.status.ABANDONED':'已中止',
    'experiment.notAnalyzable':'目前還無法分析（缺少期間日期）。',
    'experiment.insufficient':'{metric}：資料還不夠（對照期 {baseline} 天 / 實驗期 {intervention} 天，各需至少 {required} 天）',
    'experiment.metricHeading':'{metric}：',
    'experiment.baselineMean':'  對照期平均 {value}（n={count}）',
    'experiment.interventionMean':'  實驗期平均 {value}（n={count}）',
    'experiment.difference':'  差異 {value}{effect}', 'experiment.effect':'，effect size {value}',
    'experiment.associationNote':'註：這是個人層級觀察到的前後關聯，不是因果證明。時間本身的變化（季節、生活作息）無法排除。',
    'experiment.noRunning':'目前沒有進行中的實驗。',
    'experiment.stopFailed':'目前無法結束實驗，請稍後再試。',
    'experiment.stopped':'✅ 實驗 #{id}「{name}」已結束（{from} ～ {to}）。\n用 /experiment status {id} 看前後對照結果。',
  },
  en: {
    'experiment.step.name':'What would you like to call this experiment? For example, “No coffee before bed.”',
    'experiment.step.hypothesis':'What is your hypothesis? For example, “More deep sleep.” Reply “skip” if you have none.',
    'experiment.step.intervention':'What will you do? For example, “No caffeine after 2 p.m.”',
    'experiment.step.target_metric':'Which metric will you track? For example, deep sleep, Recovery, HRV, or sleep efficiency.',
    'experiment.step.duration_days':'How many days will you run it? At least 14 days is suggested. Reply with a number.',
    'experiment.begin':'🧪 Let’s set up an experiment.\n\n({step}/{total}) {question}\n\nReply “cancel” at any time to stop setup.',
    'experiment.cancel':'Okay. I have not created the experiment.',
    'experiment.metricInvalid':'I do not recognize “{input}” as a metric. Try Recovery, HRV, resting heart rate, sleep, deep sleep, REM, sleep efficiency, sleep consistency, or Strain.\n\n({step}/{total}) {question}',
    'experiment.durationInvalid':'Enter a duration between 3 and 180 days.\n\n({step}/{total}) {question}',
    'experiment.next':'({step}/{total}) {question}',
    'experiment.unnamed':'Unnamed experiment','experiment.createFailed':'I cannot create the experiment right now. Please try again later.',
    'experiment.created':'✅ Experiment #{id} has started',
    'experiment.name':'Name: {name}', 'experiment.hypothesis':'Hypothesis: {value}',
    'experiment.intervention':'Plan: {value}','experiment.target':'Metric: {metric}',
    'experiment.period':'Period: {from}–{to} ({days} days)',
    'experiment.baselinePeriod':'Baseline period: {from}–{to}',
    'experiment.finishHint':'Use /experiment stop when finished to see a before and after comparison.',
    'experiment.caveat':'This is an n=1 personal comparison. It can show an association, not prove cause.',
    'experiment.none':'There are no experiments yet. Use /experiment create to start one.',
    'experiment.listTitle':'🧪 Experiments','experiment.listEntry':'#{id} {name}  [{status}]',
    'experiment.listMetric':'   Metric: {metrics}','experiment.notSpecified':'not specified',
    'experiment.listPeriod':'   Period: {from}–{to}', 'experiment.inProgress':'in progress',
    'experiment.statusTitle':'🧪 #{id} {name}','experiment.status':'Status: {status}',
    'experiment.status.RUNNING':'in progress','experiment.status.COMPLETED':'completed',
    'experiment.status.CANCELLED':'cancelled','experiment.status.UNKNOWN':'unknown',
    'experiment.status.DRAFT':'draft','experiment.status.ABANDONED':'abandoned',
    'experiment.notAnalyzable':'I cannot analyze this yet because the period dates are missing.',
    'experiment.insufficient':'{metric}: too little data (baseline {baseline} days / experiment {intervention} days; at least {required} days each)',
    'experiment.metricHeading':'{metric}:',
    'experiment.baselineMean':'  Baseline average {value} (n={count})',
    'experiment.interventionMean':'  Experiment average {value} (n={count})',
    'experiment.difference':'  Difference {value}{effect}', 'experiment.effect':', effect size {value}',
    'experiment.associationNote':'This is an observed personal before and after association, not proof of cause. Changes over time, including season and routine, cannot be ruled out.',
    'experiment.noRunning':'There is no active experiment.',
    'experiment.stopFailed':'I cannot end the experiment right now. Please try again later.',
    'experiment.stopped':'✅ Experiment #{id} “{name}” ended ({from}–{to}).\nUse /experiment status {id} for the before and after comparison.',
  },
  vi: {
    'experiment.step.name':'Bạn muốn đặt tên thử nghiệm là gì? Ví dụ “Không uống cà phê trước khi ngủ”.',
    'experiment.step.hypothesis':'Giả thuyết của bạn là gì? Ví dụ “Ngủ sâu nhiều hơn”. Trả lời “bỏ qua” nếu chưa có.',
    'experiment.step.intervention':'Bạn sẽ thực hiện điều gì? Ví dụ “Không dùng caffeine sau 14:00”.',
    'experiment.step.target_metric':'Bạn sẽ theo dõi chỉ số nào? Ví dụ ngủ sâu, Phục hồi, HRV hoặc hiệu quả giấc ngủ.',
    'experiment.step.duration_days':'Bạn sẽ làm trong bao nhiêu ngày? Nên có ít nhất 14 ngày. Hãy trả lời bằng số.',
    'experiment.begin':'🧪 Hãy thiết lập thử nghiệm.\n\n({step}/{total}) {question}\n\nBạn có thể trả lời “hủy” bất cứ lúc nào để dừng.',
    'experiment.cancel':'Được. Tôi chưa tạo thử nghiệm này.',
    'experiment.metricInvalid':'Tôi chưa nhận ra “{input}” là chỉ số. Bạn có thể dùng Phục hồi, HRV, nhịp tim lúc nghỉ, giấc ngủ, ngủ sâu, REM, hiệu quả giấc ngủ, tính đều đặn của giấc ngủ hoặc Strain.\n\n({step}/{total}) {question}',
    'experiment.durationInvalid':'Hãy nhập thời lượng từ 3 đến 180 ngày.\n\n({step}/{total}) {question}',
    'experiment.next':'({step}/{total}) {question}',
    'experiment.unnamed':'Thử nghiệm chưa đặt tên','experiment.createFailed':'Hiện tôi chưa thể tạo thử nghiệm. Vui lòng thử lại sau.',
    'experiment.created':'✅ Thử nghiệm #{id} đã bắt đầu',
    'experiment.name':'Tên: {name}', 'experiment.hypothesis':'Giả thuyết: {value}',
    'experiment.intervention':'Cách thực hiện: {value}','experiment.target':'Chỉ số: {metric}',
    'experiment.period':'Giai đoạn: {from}–{to} ({days} ngày)',
    'experiment.baselinePeriod':'Giai đoạn cơ sở: {from}–{to}',
    'experiment.finishHint':'Dùng /experiment stop khi kết thúc để xem so sánh trước và sau.',
    'experiment.caveat':'Đây là phép so sánh cá nhân n=1. Nó có thể cho thấy mối liên hệ, không chứng minh nguyên nhân.',
    'experiment.none':'Hiện chưa có thử nghiệm. Dùng /experiment create để bắt đầu.',
    'experiment.listTitle':'🧪 Các thử nghiệm','experiment.listEntry':'#{id} {name}  [{status}]',
    'experiment.listMetric':'   Chỉ số: {metrics}','experiment.notSpecified':'chưa chọn',
    'experiment.listPeriod':'   Giai đoạn: {from}–{to}', 'experiment.inProgress':'đang diễn ra',
    'experiment.statusTitle':'🧪 #{id} {name}','experiment.status':'Trạng thái: {status}',
    'experiment.status.RUNNING':'đang diễn ra','experiment.status.COMPLETED':'đã hoàn tất',
    'experiment.status.CANCELLED':'đã hủy','experiment.status.UNKNOWN':'chưa rõ',
    'experiment.status.DRAFT':'bản nháp','experiment.status.ABANDONED':'đã dừng',
    'experiment.notAnalyzable':'Tôi chưa thể phân tích vì thiếu ngày bắt đầu hoặc kết thúc.',
    'experiment.insufficient':'{metric}: chưa đủ dữ liệu (giai đoạn cơ sở {baseline} ngày / thử nghiệm {intervention} ngày; mỗi giai đoạn cần ít nhất {required} ngày)',
    'experiment.metricHeading':'{metric}:',
    'experiment.baselineMean':'  Trung bình giai đoạn cơ sở {value} (n={count})',
    'experiment.interventionMean':'  Trung bình giai đoạn thử nghiệm {value} (n={count})',
    'experiment.difference':'  Chênh lệch {value}{effect}', 'experiment.effect':', mức ảnh hưởng {value}',
    'experiment.associationNote':'Đây là mối liên hệ quan sát khi so sánh trước và sau ở một người, không chứng minh nguyên nhân. Không thể loại trừ thay đổi theo thời gian, như mùa hoặc nếp sinh hoạt.',
    'experiment.noRunning':'Hiện không có thử nghiệm nào đang diễn ra.',
    'experiment.stopFailed':'Hiện tôi chưa thể kết thúc thử nghiệm. Vui lòng thử lại sau.',
    'experiment.stopped':'✅ Thử nghiệm #{id} “{name}” đã kết thúc ({from}–{to}).\nDùng /experiment status {id} để xem so sánh trước và sau.',
  },
});
