export const ROUTER_CATALOG = Object.freeze({
  'zh-TW': {
    'router.noData':'目前還沒有足夠的 WHOOP 資料可以回答這個問題。\n\n等手錶開始同步之後我就能分析了。在那之前你還是可以用 /log 記錄事件，那些紀錄會完整保存下來，之後就能拿來對照。',
    'router.unknownMetric':'我還不認得這個指標。可以問 HRV、靜息心率、恢復、睡眠、Strain 等。',
    'router.liveHeartRate':'我看不到你「現在」的心跳 —— WHOOP 的開發者 API 沒有即時心率，我這邊只有睡眠期間量到的靜息心率、以及已完成週期的平均／最高心率。',
    'router.restingHeartRate':'今天的靜息心率是 {value}（這是睡眠時的值，不是你當下的心跳）。',
    'router.liveHeartRateAdvice':'如果你手邊的錶或 App 正顯示一個數字，跟我說多少，我可以幫你對照看看。',
    'router.unsupported':'{metric}不在這個系統拿得到的資料範圍內，所以我沒辦法回答這一題。',
    'router.noMetricRecords':'我這邊還沒有{metric}的任何一筆紀錄。',
    'router.insufficientHistory':'{metric}目前的樣本還太少，還不夠下結論。再累積幾天就可以了。',
    'router.calibrating':'{metric}今天的數值有，但還在 WHOOP 的校正期，暫時不做趨勢判斷。',
    'router.ownershipUnavailable':'我這邊暫時處理不了，稍後再說一次好嗎？（你的訊息沒有被記錄）',
    'router.ownershipBusy':'我還在處理你上一句回覆，稍等一下再說一次好嗎？',
    'router.saved':'✅ 已記錄：{event}',
    'router.compoundSaved':'我先幫你記下{factor}。',
    'router.unknownCommand':'不認得指令 /{command}。輸入 /help 看可用指令。',
    'router.thirdPartyUnknown':'這題我沒辦法幫你判斷 —— 我看不到他的資料，也不該用你的數據去回答關於他的問題。\n\n如果他的狀況讓你不放心，尤其是有呼吸困難、胸痛、意識不清或叫不醒的情況，請直接尋求醫療協助。',
    'router.generalUnknown':'這個問題我沒有足夠把握給你一般性的說明，我不想憑印象回答健康問題。\n\n如果你想問的是自己的數據，可以直接問「我今天狀態怎樣」或「最近 HRV 如何」。',
    'router.unknownQuestion':'我不太確定你想問什麼。可以試試：\n· 我今天狀態怎樣？\n· 最近 HRV 如何？\n· 最近睡眠有沒有變差？\n· 最近 30 天最好是哪一天？\n\n或輸入 /help 看完整說明。',
    'router.recallMatched':'你今天有告訴我：{factors}。',
    'router.recallOther':'我這邊今天沒有那筆紀錄，只有{factors}。\n\n我只看得到你告訴我的事，所以沒有紀錄不代表沒發生。',
    'router.recallEmpty':'我這邊今天還沒有你的任何紀錄。\n\n我只看得到你告訴我的事，所以沒有紀錄不代表沒發生 —— 想記的話跟我說一聲就好。',
    'router.pendingNo':'好，那我先記著這幾天的數字，繼續幫你留意。',
    'router.proactiveNo':'好，我先記著這件事，會繼續留意後續的數字。',
    'router.proactiveNoAfterClarify':'好，我先記著，會繼續留意。',
    'router.whichDay':'我想確認一下：這是哪一天的事？（今天、昨天，還是前天？）',
    'router.ownershipLost':'我這邊處理到一半被中斷了，這則先沒有記錄；需要的話再跟我說一次。',
    'router.savedNoData':'{saved}\n\n目前還沒有 WHOOP 資料，等同步之後我就能把這些對照著看。',
    'router.notedNoData':'我先記下來了。目前還沒有 WHOOP 資料，等同步之後就能分析。',
    'router.proactiveClarify':'不好意思我沒有聽懂——可以更明確地說「有」還是「沒有」嗎？（例如「喝了兩杯」或「沒有」）',
    'router.proactiveStillUnexplained':'目前累積的資料還不足以確認這是不是解釋，我會繼續追蹤。',
    'router.noted':'我先記下來了。',
    'router.experimentHelp':'🧪 實驗指令：\n\n/experiment create — 建立一個新實驗（我會一步步問你）\n/experiment list — 列出所有實驗\n/experiment status [id] — 看前後對照結果\n/experiment stop [id] — 結束進行中的實驗',
    'conversation.followUp':'昨天有喝酒、旅行、生病、壓力特別大，或睡得特別晚嗎？\n（直接回我就好，例如「喝了三杯酒」或「沒有」。我會記下來，之後就能幫你把這些對照著看。）',
    'journal.negated':'我這邊只能記下發生過的事，沒有辦法記「沒有發生」這種紀錄。\n\n所以這次我什麼都沒有記。沒有紀錄本身就代表我沒收到那件事 —— 真的發生了再跟我說一聲就好。',
  },
  en: {
    'router.noData':'There is not enough WHOOP data to answer yet. Once your device starts syncing, I can analyze it. You can still use /log to record events; those entries will be saved for later comparisons.',
    'router.unknownMetric':'I do not recognize that metric. You can ask about HRV, resting heart rate, Recovery, sleep, or Strain.',
    'router.liveHeartRate':'I cannot see your heart rate right now. The WHOOP developer API does not provide live heart rate. I only have resting heart rate measured during sleep and average or peak rates from completed cycles.',
    'router.restingHeartRate':'Today’s resting heart rate was {value}. It was measured during sleep, not at this moment.',
    'router.liveHeartRateAdvice':'If your watch or app shows a current value, tell me and I can help you put it in context.',
    'router.unsupported':'{metric} is outside the data this system can access, so I cannot answer that question.',
    'router.noMetricRecords':'I do not have any records for {metric} yet.',
    'router.insufficientHistory':'There are too few {metric} samples to draw a conclusion yet. A few more days of data may help.',
    'router.calibrating':'I have today’s {metric} value, but WHOOP is still calibrating, so I cannot assess a trend yet.',
    'router.ownershipUnavailable':'I cannot process that reply right now. Please try again later. Nothing was recorded.',
    'router.ownershipBusy':'I am still processing your previous reply. Please wait a moment and try again.',
    'router.saved':'✅ Recorded: {event}',
    'router.compoundSaved':'I recorded {factor} first.',
    'router.unknownCommand':'I do not recognize /{command}. Use /help for available commands.',
    'router.thirdPartyUnknown':'I cannot judge that person’s situation. I cannot see their data and should not use yours to answer about them.\n\nIf you are concerned, especially if they have trouble breathing, chest pain, confusion, or cannot be awakened, seek medical help.',
    'router.generalUnknown':'I am not confident enough to give a general explanation for that health question, so I will not guess.\n\nFor your own data, you can ask “How am I doing today?” or “How has my HRV been lately?”',
    'router.unknownQuestion':'I am not sure what you mean. You could ask:\n· How am I doing today?\n· How has my HRV been lately?\n· Has my sleep been getting worse?\n· What was my best day in the past 30 days?\n\nUse /help for the full guide.',
    'router.recallMatched':'You told me about {factors} today.',
    'router.recallOther':'I do not have that entry for today; I only have {factors}.\n\nI can see only what you told me. No entry does not mean it did not happen.',
    'router.recallEmpty':'I do not have any entries from you today.\n\nI can see only what you tell me, so no entry does not mean something did not happen. Tell me if you want to record it.',
    'router.pendingNo':'Okay. I will keep an eye on the readings over the next few days.',
    'router.proactiveNo':'Okay. I will keep that in mind and watch the readings that follow.',
    'router.proactiveNoAfterClarify':'Okay. I will keep an eye on it.',
    'router.whichDay':'Which day was that: today, yesterday, or the day before?',
    'router.ownershipLost':'Processing was interrupted, so I did not record this. Please tell me again if needed.',
    'router.savedNoData':'{saved}\n\nThere is no WHOOP data yet. Once it syncs, I can compare the two.',
    'router.notedNoData':'I have noted that. There is no WHOOP data yet; I can analyze it after syncing.',
    'router.proactiveClarify':'Sorry, I did not understand. Could you say more clearly whether the answer is yes or no? For example, “three drinks” or “no.”',
    'router.proactiveStillUnexplained':'There is not enough data to confirm whether this explains the change. I will keep watching.',
    'router.noted':'I have noted that.',
    'router.experimentHelp':'🧪 Experiment commands:\n\n/experiment create — Set up a new experiment step by step\n/experiment list — List your experiments\n/experiment status [id] — Compare before and after\n/experiment stop [id] — End an active experiment',
    'conversation.followUp':'Did you drink alcohol, travel, feel ill or unusually stressed, or go to bed very late yesterday?\n(Just reply, for example, “three drinks” or “no.” I will save the answer for future comparisons.)',
    'journal.negated':'I can record events that happened, but this Journal cannot store an event that did not happen.\n\nI did not record anything this time. Tell me if an event does happen.',
  },
  vi: {
    'router.noData':'Hiện chưa có đủ dữ liệu WHOOP để trả lời. Khi thiết bị bắt đầu đồng bộ, tôi có thể phân tích. Bạn vẫn có thể dùng /log để ghi sự kiện; các ghi chép đó sẽ được lưu để đối chiếu sau.',
    'router.unknownMetric':'Tôi chưa nhận ra chỉ số đó. Bạn có thể hỏi về HRV, nhịp tim lúc nghỉ, Phục hồi, giấc ngủ hoặc Strain.',
    'router.liveHeartRate':'Tôi không xem được nhịp tim của bạn ngay lúc này. API dành cho nhà phát triển của WHOOP không cung cấp nhịp tim trực tiếp. Tôi chỉ có nhịp tim lúc nghỉ đo khi ngủ và nhịp trung bình hoặc cao nhất của các chu kỳ đã hoàn tất.',
    'router.restingHeartRate':'Nhịp tim lúc nghỉ hôm nay là {value}. Đây là giá trị đo khi ngủ, không phải nhịp tim hiện tại.',
    'router.liveHeartRateAdvice':'Nếu đồng hồ hoặc ứng dụng đang hiển thị một giá trị, bạn có thể cho tôi biết để cùng xem trong bối cảnh.',
    'router.unsupported':'{metric} nằm ngoài dữ liệu hệ thống này có thể truy cập, nên tôi không thể trả lời câu hỏi đó.',
    'router.noMetricRecords':'Tôi chưa có bản ghi nào cho {metric}.',
    'router.insufficientHistory':'Hiện có quá ít mẫu {metric} để kết luận. Thêm vài ngày dữ liệu có thể giúp ích.',
    'router.calibrating':'Tôi có giá trị {metric} hôm nay, nhưng WHOOP vẫn đang hiệu chuẩn nên chưa thể đánh giá xu hướng.',
    'router.ownershipUnavailable':'Hiện tôi chưa thể xử lý câu trả lời đó. Vui lòng thử lại sau. Chưa có gì được ghi lại.',
    'router.ownershipBusy':'Tôi vẫn đang xử lý câu trả lời trước của bạn. Hãy đợi một chút rồi thử lại.',
    'router.saved':'✅ Đã ghi: {event}',
    'router.compoundSaved':'Tôi đã ghi lại {factor} trước.',
    'router.unknownCommand':'Tôi không nhận ra lệnh /{command}. Dùng /help để xem các lệnh có thể dùng.',
    'router.thirdPartyUnknown':'Tôi không thể đánh giá tình trạng của người đó. Tôi không thấy dữ liệu của họ và không nên dùng dữ liệu của bạn để trả lời về họ.\n\nNếu bạn lo lắng, nhất là khi họ khó thở, đau ngực, lú lẫn hoặc không thể đánh thức, hãy tìm trợ giúp y tế.',
    'router.generalUnknown':'Tôi chưa đủ chắc chắn để giải thích chung về câu hỏi sức khỏe đó nên sẽ không đoán.\n\nĐể hỏi về dữ liệu của mình, bạn có thể hỏi “Hôm nay tình trạng của tôi thế nào?” hoặc “HRV gần đây ra sao?”',
    'router.unknownQuestion':'Tôi chưa rõ ý bạn. Bạn có thể hỏi:\n· Hôm nay tình trạng của tôi thế nào?\n· HRV gần đây ra sao?\n· Giấc ngủ của tôi có kém đi không?\n· Ngày tốt nhất trong 30 ngày qua là ngày nào?\n\nDùng /help để xem hướng dẫn đầy đủ.',
    'router.recallMatched':'Hôm nay bạn đã cho tôi biết về {factors}.',
    'router.recallOther':'Hôm nay tôi không có ghi chép đó; tôi chỉ có {factors}.\n\nTôi chỉ thấy những gì bạn nói. Không có ghi chép không có nghĩa sự việc không xảy ra.',
    'router.recallEmpty':'Hôm nay tôi chưa có ghi chép nào từ bạn.\n\nTôi chỉ thấy những gì bạn nói, nên không có ghi chép không có nghĩa sự việc không xảy ra. Hãy nói nếu bạn muốn ghi lại.',
    'router.pendingNo':'Được. Tôi sẽ tiếp tục theo dõi các số liệu trong vài ngày tới.',
    'router.proactiveNo':'Được. Tôi sẽ ghi nhớ và theo dõi các số liệu tiếp theo.',
    'router.proactiveNoAfterClarify':'Được. Tôi sẽ tiếp tục theo dõi.',
    'router.whichDay':'Việc đó xảy ra ngày nào: hôm nay, hôm qua hay hôm kia?',
    'router.ownershipLost':'Quá trình xử lý bị gián đoạn nên tôi chưa ghi lại điều này. Hãy nói lại nếu cần.',
    'router.savedNoData':'{saved}\n\nHiện chưa có dữ liệu WHOOP. Khi dữ liệu được đồng bộ, tôi có thể đối chiếu.',
    'router.notedNoData':'Tôi đã ghi nhận. Hiện chưa có dữ liệu WHOOP; tôi có thể phân tích sau khi đồng bộ.',
    'router.proactiveClarify':'Xin lỗi, tôi chưa hiểu. Bạn có thể nói rõ hơn là có hay không? Ví dụ “ba ly” hoặc “không”.',
    'router.proactiveStillUnexplained':'Hiện chưa đủ dữ liệu để xác nhận liệu điều này giải thích thay đổi đó hay không. Tôi sẽ tiếp tục theo dõi.',
    'router.noted':'Tôi đã ghi nhận.',
    'router.experimentHelp':'🧪 Lệnh thử nghiệm:\n\n/experiment create — Tạo thử nghiệm mới theo từng bước\n/experiment list — Liệt kê thử nghiệm\n/experiment status [id] — So sánh trước và sau\n/experiment stop [id] — Kết thúc thử nghiệm đang diễn ra',
    'conversation.followUp':'Hôm qua bạn có uống rượu bia, đi xa, bị bệnh, căng thẳng hơn thường lệ hoặc đi ngủ rất muộn không?\n(Bạn chỉ cần trả lời, ví dụ “ba ly” hoặc “không”. Tôi sẽ lưu lại để đối chiếu về sau.)',
    'journal.negated':'Tôi có thể ghi lại sự kiện đã xảy ra, nhưng Journal này không thể lưu một sự kiện không xảy ra.\n\nLần này tôi chưa ghi gì. Hãy cho tôi biết nếu sự kiện đó xảy ra.',
  },
});
