/** Fixed health-assertion phrasing; no claims originate in translation. */
export const ASSERTION_CATALOG = Object.freeze({
  'zh-TW': {
    'qa.header':'📊 {date} 的狀態', 'qa.empty':'目前還沒有足夠的資料可以回答這個問題。',
    'qa.unavailable':'目前拿不到：{metrics}', 'qa.join':'、',
    'qa.baseline':'{metric}基準 {value}', 'qa.change':'{metric}變化 {value}',
    'qa.trend':'{metric}趨勢 {value}', 'qa.value':'{metric} {value}',
    'qa.metric.recovery':'恢復','qa.metric.hrv':'HRV','qa.metric.rhr':'靜息心率',
    'qa.metric.respiratory_rate':'呼吸率','qa.metric.sleep_total':'睡眠',
    'qa.metric.slow_wave':'深睡','qa.metric.rem':'REM',
    'qa.metric.sleep_performance':'睡眠表現','qa.metric.sleep_debt':'睡眠債',
    'qa.metric.sleep_consistency':'睡眠一致性','qa.metric.sleep_efficiency':'睡眠效率',
    'qa.metric.disturbance_count':'擾動次數','qa.metric.strain':'Strain',
    'qa.metric.spo2':'血氧','qa.metric.skin_temp':'皮膚溫度',
    'qa.metric.weight':'體重','qa.metric.steps':'步數',
    'qa.metric.vo2_max':'最大攝氧量','qa.metric.max_heart_rate':'最大心率',
    'qa.metric.lean_body_mass':'去脂體重','qa.metric.calories':'熱量',
  },
  en: {
    'qa.header':'📊 Status for {date}', 'qa.empty':'There is not enough data yet to answer this question.',
    'qa.unavailable':'Currently unavailable: {metrics}', 'qa.join':', ',
    'qa.baseline':'{metric} baseline: {value}', 'qa.change':'{metric} change: {value}',
    'qa.trend':'{metric} trend: {value}', 'qa.value':'{metric}: {value}',
    'qa.metric.recovery':'Recovery','qa.metric.hrv':'HRV','qa.metric.rhr':'Resting heart rate',
    'qa.metric.respiratory_rate':'Respiratory rate','qa.metric.sleep_total':'Sleep',
    'qa.metric.slow_wave':'Deep sleep','qa.metric.rem':'REM',
    'qa.metric.sleep_performance':'Sleep performance','qa.metric.sleep_debt':'Sleep debt',
    'qa.metric.sleep_consistency':'Sleep consistency','qa.metric.sleep_efficiency':'Sleep efficiency',
    'qa.metric.disturbance_count':'Disturbances','qa.metric.strain':'Strain',
    'qa.metric.spo2':'Blood oxygen','qa.metric.skin_temp':'Skin temperature',
    'qa.metric.weight':'Weight','qa.metric.steps':'Steps',
    'qa.metric.vo2_max':'VO₂ max','qa.metric.max_heart_rate':'Maximum heart rate',
    'qa.metric.lean_body_mass':'Lean body mass','qa.metric.calories':'Calories',
  },
  vi: {
    'qa.header':'📊 Tình trạng ngày {date}', 'qa.empty':'Hiện chưa đủ dữ liệu để trả lời câu hỏi này.',
    'qa.unavailable':'Hiện chưa có: {metrics}', 'qa.join':', ',
    'qa.baseline':'Mức nền {metric}: {value}', 'qa.change':'Mức thay đổi {metric}: {value}',
    'qa.trend':'Xu hướng {metric}: {value}', 'qa.value':'{metric}: {value}',
    'qa.metric.recovery':'Phục hồi','qa.metric.hrv':'HRV','qa.metric.rhr':'Nhịp tim nghỉ',
    'qa.metric.respiratory_rate':'Nhịp thở','qa.metric.sleep_total':'Giấc ngủ',
    'qa.metric.slow_wave':'Ngủ sâu','qa.metric.rem':'REM',
    'qa.metric.sleep_performance':'Hiệu quả giấc ngủ','qa.metric.sleep_debt':'Thiếu ngủ tích lũy',
    'qa.metric.sleep_consistency':'Độ đều đặn giấc ngủ','qa.metric.sleep_efficiency':'Hiệu suất giấc ngủ',
    'qa.metric.disturbance_count':'Số lần gián đoạn','qa.metric.strain':'Strain',
    'qa.metric.spo2':'Oxy máu','qa.metric.skin_temp':'Nhiệt độ da',
    'qa.metric.weight':'Cân nặng','qa.metric.steps':'Số bước',
    'qa.metric.vo2_max':'VO₂ tối đa','qa.metric.max_heart_rate':'Nhịp tim tối đa',
    'qa.metric.lean_body_mass':'Khối lượng cơ thể không mỡ','qa.metric.calories':'Calo',
  },
});
