export const AUXILIARY_CATALOG = Object.freeze({
  'zh-TW': {
    'evidence.title':'🔍 目前的證據', 'evidence.empty':'目前還沒有足夠的資料形成任何結論，所以也沒有證據可以給你。等 WHOOP 開始同步、累積一段時間之後，我才會開始建立長期規律。',
    'evidence.noSupportedConclusion':'目前還沒有累積足夠的資料形成任何有證據支持的結論。',
    'evidence.metric':'· {metric}', 'evidence.metricUnknown':'一項個人觀察',
    'evidence.method':'  方法：{method}', 'evidence.samples':'  樣本數：{count}',
    'evidence.effect':'  效果量：{value}', 'evidence.confidence':'  資料充分度：{level}',
    'evidence.range':'  區間：{from} ～ {to}', 'evidence.warning':'  ⚠️ 這項證據有資料限制。',
    'evidence.note':'註：以上全部是個人層級觀察到的關聯，不是因果關係，也不是醫學結論。',
    'evidence.unknown':'不明',
    'evidence.method.correlation':'相關分析','evidence.method.association':'Journal 關聯',
    'evidence.method.regression':'迴歸分析','evidence.method.prediction':'預測評估',
    'evidence.method.experiment':'前後對照','evidence.method.trend':'趨勢分析',
    'evidence.method.deviation':'個人基準偏離','evidence.method.other':'資料分析',
    'evidence.level.INSUFFICIENT':'資料不足','evidence.level.LOW_CONFIDENCE':'低',
    'evidence.level.MODERATE':'中等','evidence.level.BETTER_SUPPORTED':'支持較多',
    'cost.title':'💰 AI 使用成本', 'cost.empty':'目前沒有可用的用量紀錄。',
    'cost.today':'今天（{date}）', 'cost.month':'本月（{month}）',
    'cost.noCalls':'  （沒有呼叫紀錄）', 'cost.unavailable':'成本無法估算',
    'cost.group':'  {name}: {value}', 'cost.total':'  合計：{value}',
    'cost.groupName.Daily':'每日簡報','cost.groupName.Weekly':'每週回顧',
    'cost.groupName.QA':'問答','cost.groupName.Parsing':'解析',
    'cost.groupName.Other':'其他',
    'cost.calls':'  （{count} 次呼叫；失敗 {failed} 次）',
    'cost.unknownCalls':'  ⚠️ {count} 次沒有 token 用量資料，成本未估算',
    'cost.note':'註：成本依內建價格表估算，供參考用；價格表可能與實際帳單有落差。',
    'healthspan.title':'🧬 長期生理盤點',
    'healthspan.status':'狀態：{status}', 'healthspan.coverage':'資料覆蓋：{usable}/{scoped} 項指標',
    'healthspan.history':'累積歷史：約{tier}', 'healthspan.version':'盤點方法：{version}',
    'healthspan.method.v0':'初版盤點方法','healthspan.method.unknown':'版本未提供',
    'healthspan.empty':'還沒有可以盤點的資料。等 WHOOP 開始同步之後就會自動開始。',
    'healthspan.metrics':'目前盤點到的指標：',
    'healthspan.metric':'  {mark} {metric}（{count} 筆）',
    'healthspan.noScore':'目前不會給你一個綜合分數或推估年齡。資料底座已經在累積，但還沒有一套經過驗證的計分方式；在那之前給出一個數字，只會讓你以為它有意義。',
    'healthspan.note':'註：這是本系統自己的長期生理盤點，與 WHOOP App 內的任何評分無關。',
    'healthspan.maturity.NO_DATA':'尚未開始累積','healthspan.maturity.WARMING_UP':'校準中',
    'healthspan.maturity.LIMITED':'資料有限','healthspan.maturity.STRUCTURALLY_READY':'資料充足',
    'healthspan.maturity.QUALIFIED':'已啟用','healthspan.maturity.UNKNOWN':'狀態不明',
    'healthspan.tier.30':'一個月','healthspan.tier.60':'兩個月',
    'healthspan.tier.90':'三個月','healthspan.tier.180':'半年',
    'healthspan.metric.sleep_duration':'睡眠時間','healthspan.metric.sleep_consistency':'睡眠規律',
    'healthspan.metric.resting_heart_rate':'靜息心率','healthspan.metric.hrv':'HRV',
    'healthspan.metric.recovery':'恢復','healthspan.metric.respiratory_rate':'呼吸率',
    'healthspan.metric.strain':'Strain','healthspan.metric.workout_volume':'運動量',
    'healthspan.metric.hr_zone_1_3':'心率區間 1–3','healthspan.metric.hr_zone_4_5':'心率區間 4–5',
    'healthspan.metric.strength_activity':'肌力活動','healthspan.metric.weight':'體重',
    'healthspan.metric.max_heart_rate':'最高心率','healthspan.metric.spo2':'血氧',
    'healthspan.metric.skin_temp':'皮膚溫度','healthspan.metric.steps':'步數',
    'healthspan.metric.vo2_max':'最大攝氧量','healthspan.metric.lean_body_mass':'淨體重',
    'healthspan.metric.unknown':'其他指標',
  },
  en: {
    'evidence.title':'🔍 Current evidence', 'evidence.empty':'There is not enough data for a supported conclusion yet. After WHOOP syncs and more history accumulates, I can begin identifying longer-term patterns.',
    'evidence.noSupportedConclusion':'There is not enough data for an evidence-supported conclusion yet.',
    'evidence.metric':'· {metric}', 'evidence.metricUnknown':'a personal observation',
    'evidence.method':'  Method: {method}', 'evidence.samples':'  Sample size: {count}',
    'evidence.effect':'  Effect size: {value}', 'evidence.confidence':'  Data sufficiency: {level}',
    'evidence.range':'  Period: {from}–{to}', 'evidence.warning':'  ⚠️ This evidence has data limitations.',
    'evidence.note':'These are personal observed associations, not proof of cause or medical conclusions.',
    'evidence.unknown':'unknown',
    'evidence.method.correlation':'correlation','evidence.method.association':'Journal association',
    'evidence.method.regression':'regression','evidence.method.prediction':'prediction evaluation',
    'evidence.method.experiment':'before and after comparison','evidence.method.trend':'trend analysis',
    'evidence.method.deviation':'personal baseline deviation','evidence.method.other':'data analysis',
    'evidence.level.INSUFFICIENT':'insufficient','evidence.level.LOW_CONFIDENCE':'low',
    'evidence.level.MODERATE':'moderate','evidence.level.BETTER_SUPPORTED':'better supported',
    'cost.title':'💰 AI usage cost', 'cost.empty':'There are no usable usage records yet.',
    'cost.today':'Today ({date})', 'cost.month':'This month ({month})',
    'cost.noCalls':'  (no calls recorded)', 'cost.unavailable':'cost unavailable',
    'cost.group':'  {name}: {value}', 'cost.total':'  Total: {value}',
    'cost.groupName.Daily':'Daily briefing','cost.groupName.Weekly':'Weekly review',
    'cost.groupName.QA':'Q&A','cost.groupName.Parsing':'Parsing',
    'cost.groupName.Other':'Other',
    'cost.calls':'  ({count} calls; {failed} failed)',
    'cost.unknownCalls':'  ⚠️ {count} calls have no token usage data, so their cost was not estimated',
    'cost.note':'Costs are estimated from the built-in price table for reference and may differ from the actual bill.',
    'healthspan.title':'🧬 Longer-term health overview',
    'healthspan.status':'Status: {status}', 'healthspan.coverage':'Data coverage: {usable}/{scoped} metrics',
    'healthspan.history':'History accumulated: about {tier}', 'healthspan.version':'Review method: {version}',
    'healthspan.method.v0':'initial review method','healthspan.method.unknown':'version unavailable',
    'healthspan.empty':'There is no data to review yet. This overview starts automatically after WHOOP syncs.',
    'healthspan.metrics':'Metrics currently covered:',
    'healthspan.metric':'  {mark} {metric} ({count} records)',
    'healthspan.noScore':'I will not provide a combined score or estimated age. Data is accumulating, but there is no validated scoring method. A number now would imply more meaning than the evidence supports.',
    'healthspan.note':'This is this system’s own longer-term health overview, separate from scores in the WHOOP app.',
    'healthspan.maturity.NO_DATA':'no data yet','healthspan.maturity.WARMING_UP':'calibrating',
    'healthspan.maturity.LIMITED':'limited data','healthspan.maturity.STRUCTURALLY_READY':'sufficient data',
    'healthspan.maturity.QUALIFIED':'active','healthspan.maturity.UNKNOWN':'status unknown',
    'healthspan.tier.30':'one month','healthspan.tier.60':'two months',
    'healthspan.tier.90':'three months','healthspan.tier.180':'six months',
    'healthspan.metric.sleep_duration':'Sleep duration','healthspan.metric.sleep_consistency':'Sleep consistency',
    'healthspan.metric.resting_heart_rate':'Resting heart rate','healthspan.metric.hrv':'HRV',
    'healthspan.metric.recovery':'Recovery','healthspan.metric.respiratory_rate':'Respiratory rate',
    'healthspan.metric.strain':'Strain','healthspan.metric.workout_volume':'Workout volume',
    'healthspan.metric.hr_zone_1_3':'Heart rate zones 1–3','healthspan.metric.hr_zone_4_5':'Heart rate zones 4–5',
    'healthspan.metric.strength_activity':'Strength activity','healthspan.metric.weight':'Weight',
    'healthspan.metric.max_heart_rate':'Maximum heart rate','healthspan.metric.spo2':'Blood oxygen',
    'healthspan.metric.skin_temp':'Skin temperature','healthspan.metric.steps':'Steps',
    'healthspan.metric.vo2_max':'VO₂ max','healthspan.metric.lean_body_mass':'Lean body mass',
    'healthspan.metric.unknown':'Other metric',
  },
  vi: {
    'evidence.title':'🔍 Bằng chứng hiện có', 'evidence.empty':'Hiện chưa đủ dữ liệu để đưa ra kết luận được hỗ trợ. Sau khi WHOOP đồng bộ và có thêm lịch sử, tôi có thể bắt đầu nhận diện quy luật dài hạn.',
    'evidence.noSupportedConclusion':'Hiện chưa đủ dữ liệu để đưa ra kết luận có bằng chứng hỗ trợ.',
    'evidence.metric':'· {metric}', 'evidence.metricUnknown':'một quan sát cá nhân',
    'evidence.method':'  Phương pháp: {method}', 'evidence.samples':'  Cỡ mẫu: {count}',
    'evidence.effect':'  Mức ảnh hưởng: {value}', 'evidence.confidence':'  Mức đầy đủ dữ liệu: {level}',
    'evidence.range':'  Giai đoạn: {from}–{to}', 'evidence.warning':'  ⚠️ Bằng chứng này có giới hạn dữ liệu.',
    'evidence.note':'Đây là các mối liên hệ quan sát ở cấp độ cá nhân, không chứng minh nguyên nhân và không phải kết luận y khoa.',
    'evidence.unknown':'chưa rõ',
    'evidence.method.correlation':'phân tích tương quan','evidence.method.association':'liên hệ với Journal',
    'evidence.method.regression':'phân tích hồi quy','evidence.method.prediction':'đánh giá dự đoán',
    'evidence.method.experiment':'so sánh trước và sau','evidence.method.trend':'phân tích xu hướng',
    'evidence.method.deviation':'độ lệch so với mức cơ sở cá nhân','evidence.method.other':'phân tích dữ liệu',
    'evidence.level.INSUFFICIENT':'chưa đủ','evidence.level.LOW_CONFIDENCE':'thấp',
    'evidence.level.MODERATE':'trung bình','evidence.level.BETTER_SUPPORTED':'được hỗ trợ tốt hơn',
    'cost.title':'💰 Chi phí sử dụng AI', 'cost.empty':'Hiện chưa có ghi nhận sử dụng nào có thể dùng.',
    'cost.today':'Hôm nay ({date})', 'cost.month':'Tháng này ({month})',
    'cost.noCalls':'  (chưa có lượt gọi)', 'cost.unavailable':'không thể ước tính chi phí',
    'cost.group':'  {name}: {value}', 'cost.total':'  Tổng cộng: {value}',
    'cost.groupName.Daily':'Bản tin hằng ngày','cost.groupName.Weekly':'Tổng kết hằng tuần',
    'cost.groupName.QA':'Hỏi đáp','cost.groupName.Parsing':'Phân tích cú pháp',
    'cost.groupName.Other':'Khác',
    'cost.calls':'  ({count} lượt gọi; {failed} thất bại)',
    'cost.unknownCalls':'  ⚠️ {count} lượt gọi không có dữ liệu token nên chưa ước tính chi phí',
    'cost.note':'Chi phí được ước tính theo bảng giá tích hợp để tham khảo và có thể khác hóa đơn thực tế.',
    'healthspan.title':'🧬 Tổng quan sức khỏe dài hạn',
    'healthspan.status':'Trạng thái: {status}', 'healthspan.coverage':'Dữ liệu bao phủ: {usable}/{scoped} chỉ số',
    'healthspan.history':'Lịch sử tích lũy: khoảng {tier}', 'healthspan.version':'Phương pháp đánh giá: {version}',
    'healthspan.method.v0':'phương pháp đánh giá ban đầu','healthspan.method.unknown':'không có thông tin phiên bản',
    'healthspan.empty':'Hiện chưa có dữ liệu để xem. Tổng quan sẽ tự bắt đầu sau khi WHOOP đồng bộ.',
    'healthspan.metrics':'Các chỉ số hiện được theo dõi:',
    'healthspan.metric':'  {mark} {metric} ({count} bản ghi)',
    'healthspan.noScore':'Tôi chưa đưa ra điểm tổng hợp hay tuổi ước tính. Dữ liệu đang tích lũy nhưng chưa có cách chấm điểm được kiểm chứng. Một con số lúc này sẽ khiến dữ liệu có vẻ chắc chắn hơn thực tế.',
    'healthspan.note':'Đây là tổng quan sức khỏe dài hạn của hệ thống này, tách biệt với các điểm trong ứng dụng WHOOP.',
    'healthspan.maturity.NO_DATA':'chưa có dữ liệu','healthspan.maturity.WARMING_UP':'đang hiệu chuẩn',
    'healthspan.maturity.LIMITED':'dữ liệu hạn chế','healthspan.maturity.STRUCTURALLY_READY':'dữ liệu đầy đủ',
    'healthspan.maturity.QUALIFIED':'đang hoạt động','healthspan.maturity.UNKNOWN':'chưa rõ trạng thái',
    'healthspan.tier.30':'một tháng','healthspan.tier.60':'hai tháng',
    'healthspan.tier.90':'ba tháng','healthspan.tier.180':'sáu tháng',
    'healthspan.metric.sleep_duration':'Thời lượng ngủ','healthspan.metric.sleep_consistency':'Tính đều đặn của giấc ngủ',
    'healthspan.metric.resting_heart_rate':'Nhịp tim lúc nghỉ','healthspan.metric.hrv':'HRV',
    'healthspan.metric.recovery':'Phục hồi','healthspan.metric.respiratory_rate':'Nhịp thở',
    'healthspan.metric.strain':'Strain','healthspan.metric.workout_volume':'Khối lượng vận động',
    'healthspan.metric.hr_zone_1_3':'Vùng nhịp tim 1–3','healthspan.metric.hr_zone_4_5':'Vùng nhịp tim 4–5',
    'healthspan.metric.strength_activity':'Hoạt động sức mạnh','healthspan.metric.weight':'Cân nặng',
    'healthspan.metric.max_heart_rate':'Nhịp tim tối đa','healthspan.metric.spo2':'Oxy máu',
    'healthspan.metric.skin_temp':'Nhiệt độ da','healthspan.metric.steps':'Số bước',
    'healthspan.metric.vo2_max':'VO₂ tối đa','healthspan.metric.lean_body_mass':'Khối nạc',
    'healthspan.metric.unknown':'Chỉ số khác',
  },
});
