/** Closed, application-owned report and narrative templates. */
export const BRIEFING_CATALOG = Object.freeze({
  'zh-TW': Object.freeze({
    'daily.greetingNamed':'🌅 早安，{name}', 'daily.greetingNeutral':'🌅 早安',
    'daily.recoveryValue':'恢復 {value}{light}{stage}', 'daily.recoveryMissing':'恢復 無資料{stage}',
    'daily.headerCold':'📊 今日指標', 'daily.headerWarm':'📊 指標 vs 你的基準',
    'daily.calibrating':'ℹ️ WHOOP 恢復數據還在校正中；恢復類指標只顯示數值，不做好壞判斷。',
    'daily.stageCold':'（個人基準建立中）', 'daily.stageProvisional':'（基準建立中 {count}/{target}）',
    'daily.metricMissing':'{emoji} {metric} 無資料',
    'daily.metricCold':'{emoji} {metric} {value}',
    'daily.metricReady':'{emoji} {metric} {value}{baseline}{light}',
    'daily.baseline':'（基準 {value}）', 'daily.baselinePending':'（基準建立中）',
    'daily.trendHeadStrong':'📉 趨勢提醒（多項生理訊號同時偏離）',
    'daily.trendHead':'📉 趨勢提醒',
    'daily.trendBoth':'連續偏離且逐日變差', 'daily.trendWorsening':'逐日變差',
    'daily.trendSustained':'連續 {days} 天偏離基準',
    'daily.trendLine':'· {metric} {kind}：{series}',
    'daily.trendMore':'· 另有 {count} 項指標也在偏離',
    'daily.changeHead':'🔎 今天最值得注意',
    'daily.changeAbove':'比 30 天平均高 {percent}%',
    'daily.changeBelow':'比 30 天平均低 {percent}%',
    'daily.changeLine':'· {emoji} {metric} {value}，{comparison}{zscore}',
    'daily.changeLineSimple':'· {emoji} {metric} {value}{zscore}',
    'daily.footer':'{date} · 基準 {count}/{target} 筆',
    'daily.late':'📮 補發：{date} 的晨報\n（這份資料較晚備齊，所以現在才送。）\n\n',
    'weekly.titleNamed':'📅 上週回顧（{name}）', 'weekly.titleNeutral':'📅 上週回顧',
    'weekly.range':'{start} ～ {end} · 有效 {days} 天',
    'weekly.metricMissing':'{metric} 無資料', 'weekly.metricValue':'{metric} {value}{comparison}',
    'weekly.best':'🏆 最好的一天 {date} 恢復 {value}',
    'weekly.worst':'🥀 最差的一天 {date} 恢復 {value}',
    'weekly.noPrevious':'（前一週沒有足夠資料，這次先不比較）',
    'weekly.label.recovery_score':'💪 恢復平均','weekly.label.sleep_performance':'📈 睡眠表現',
    'weekly.label.sleep_total':'🌙 睡眠時長','weekly.label.sleep_debt':'⏳ 睡眠債加成',
    'weekly.label.hrv':'❤️ HRV','weekly.label.rhr':'💓 靜息心率',
    'weekly.noComparison':'（前週無資料可比）', 'weekly.flat':'（與前週差不多）',
    'weekly.aboveZero':'（↑ 高於前週，前週基準為 0，無法算百分比）',
    'weekly.belowZero':'（↓ 低於前週，前週基準為 0，無法算百分比）',
    'weekly.moreMinutes':'（比前週多 {minutes} 分）',
    'weekly.fewerMinutes':'（比前週少 {minutes} 分）',
    'weekly.percentChange':'（{arrow} 比前週 {percent}%）',
    'narrative.recoveryFact':'恢復 {value}', 'narrative.sleepFact':'睡眠 {value}',
    'narrative.facts':'{when}{facts}。', 'narrative.noFacts':'{when}的數字我已經收到了。',
    'narrative.coldBaseline':'個人基準還在建立，這些數字目前只作紀錄，尚不能判斷是否偏離常態。',
    'narrative.calibrating':'WHOOP 恢復數據也還在校正期，這段期間的數值不適合當基準。',
    'narrative.coldAdvice':'先維持平常作息；資料累積後，判斷會更具體。',
    'narrative.metricsReady':'{when}的指標已經整理好了。',
    'narrative.flagged':'{metrics}與你的個人基準有明顯差距，值得留意。',
    'narrative.normal':'對照你的個人基準，{when}沒有特別需要留意的偏離。',
    'narrative.missingBaseline':'{metrics}的基準還在累積，{when}暫不判斷。',
    'narrative.trends':'{metrics}出現連續變化，可以多觀察幾天。',
    'narrative.ease':'{when}適合把強度放輕一點，讓身體有時間恢復。',
    'narrative.maintain':'維持目前的節奏就好。',
    'narrative.today':'今天', 'narrative.lastWeek':'上週', 'narrative.thisWeek':'這週',
    'metric.recovery':'恢復', 'metric.sleep_total':'睡眠', 'metric.slow_wave':'深睡',
    'metric.rem':'REM', 'metric.sleep_debt':'睡眠債加成',
    'metric.sleep_consistency':'睡眠一致性', 'metric.disturbance_count':'睡眠中斷次數',
    'metric.spo2':'血氧', 'metric.skin_temp':'皮膚溫度', 'metric.strain':'Strain',
    'metric.previous_day_strain':'昨日 Strain', 'metric.deep_sleep':'深睡',
    'metric.rem_sleep':'REM',
  }),
  en: Object.freeze({
    'daily.greetingNamed':'🌅 Good morning, {name}', 'daily.greetingNeutral':'🌅 Good morning',
    'daily.recoveryValue':'Recovery {value}{light}{stage}', 'daily.recoveryMissing':'Recovery unavailable{stage}',
    'daily.headerCold':'📊 Today’s metrics', 'daily.headerWarm':'📊 Metrics vs your baseline',
    'daily.calibrating':'ℹ️ WHOOP recovery data is still calibrating. Recovery metrics show values only, without an assessment.',
    'daily.stageCold':' (building your baseline)', 'daily.stageProvisional':' (building your baseline: {count}/{target})',
    'daily.metricMissing':'{emoji} {metric}: unavailable',
    'daily.metricCold':'{emoji} {metric}: {value}',
    'daily.metricReady':'{emoji} {metric}: {value}{baseline}{light}',
    'daily.baseline':' (baseline {value})', 'daily.baselinePending':' (baseline in progress)',
    'daily.trendHeadStrong':'📉 Trend alert (several signals are changing together)',
    'daily.trendHead':'📉 Trend alert',
    'daily.trendBoth':'persistently outside baseline and worsening', 'daily.trendWorsening':'worsening day by day',
    'daily.trendSustained':'outside baseline for {days} consecutive days',
    'daily.trendLine':'· {metric}: {kind} ({series})',
    'daily.trendMore':'· {count} more metrics are outside baseline',
    'daily.changeHead':'🔎 What stands out today',
    'daily.changeAbove':'{percent}% above your 30-day average',
    'daily.changeBelow':'{percent}% below your 30-day average',
    'daily.changeLine':'· {emoji} {metric}: {value}, {comparison}{zscore}',
    'daily.changeLineSimple':'· {emoji} {metric}: {value}{zscore}',
    'daily.footer':'{date} · baseline {count}/{target} records',
    'daily.late':'📮 Delayed briefing for {date}\n(The data arrived later than usual, so this briefing is reaching you now.)\n\n',
    'weekly.titleNamed':'📅 Weekly review ({name})', 'weekly.titleNeutral':'📅 Weekly review',
    'weekly.range':'{start} – {end} · {days} days with data',
    'weekly.metricMissing':'{metric}: unavailable', 'weekly.metricValue':'{metric}: {value}{comparison}',
    'weekly.best':'🏆 Best day: {date}, recovery {value}',
    'weekly.worst':'🥀 Lowest day: {date}, recovery {value}',
    'weekly.noPrevious':'(There is not enough data from the previous week to compare.)',
    'weekly.label.recovery_score':'💪 Average recovery','weekly.label.sleep_performance':'📈 Sleep performance',
    'weekly.label.sleep_total':'🌙 Sleep duration','weekly.label.sleep_debt':'⏳ Sleep debt adjustment',
    'weekly.label.hrv':'❤️ HRV','weekly.label.rhr':'💓 Resting heart rate',
    'weekly.noComparison':' (no comparable data from the previous week)', 'weekly.flat':' (about the same as last week)',
    'weekly.aboveZero':' (↑ above last week; a zero baseline prevents a percentage comparison)',
    'weekly.belowZero':' (↓ below last week; a zero baseline prevents a percentage comparison)',
    'weekly.moreMinutes':' ({minutes} min more than last week)',
    'weekly.fewerMinutes':' ({minutes} min less than last week)',
    'weekly.percentChange':' ({arrow} {percent}% vs last week)',
    'narrative.recoveryFact':'recovery {value}', 'narrative.sleepFact':'sleep {value}',
    'narrative.facts':'{when}: {facts}. ', 'narrative.noFacts':'I have your {when} data. ',
    'narrative.coldBaseline':'Your personal baseline is still being built, so these values are records rather than a judgment about your usual range. ',
    'narrative.calibrating':'WHOOP recovery data is also calibrating; these values are not yet suitable as a baseline. ',
    'narrative.coldAdvice':'Keep your usual routine for now. The picture will become clearer as more data arrives.',
    'narrative.metricsReady':'Your {when} metrics are ready. ',
    'narrative.flagged':'{metrics} differ noticeably from your personal baseline and are worth watching. ',
    'narrative.normal':'Against your personal baseline, there is no notable deviation {when}. ',
    'narrative.missingBaseline':'The baseline for {metrics} is still being built, so I am withholding an assessment {when}. ',
    'narrative.trends':'{metrics} show a sustained change; watch how they develop over the next few days. ',
    'narrative.ease':'Consider easing the intensity {when} to give your body time to recover.',
    'narrative.maintain':'Keep your current pace.',
    'narrative.today':'today', 'narrative.lastWeek':'last week', 'narrative.thisWeek':'this week',
    'metric.recovery':'Recovery', 'metric.sleep_total':'Sleep', 'metric.slow_wave':'Deep sleep',
    'metric.rem':'REM', 'metric.sleep_debt':'Sleep debt adjustment',
    'metric.sleep_consistency':'Sleep consistency', 'metric.disturbance_count':'Sleep disturbances',
    'metric.spo2':'Blood oxygen', 'metric.skin_temp':'Skin temperature', 'metric.strain':'Strain',
    'metric.previous_day_strain':'Yesterday’s Strain', 'metric.deep_sleep':'Deep sleep',
    'metric.rem_sleep':'REM',
  }),
  vi: Object.freeze({
    'daily.greetingNamed':'🌅 Chào buổi sáng, {name}', 'daily.greetingNeutral':'🌅 Chào buổi sáng',
    'daily.recoveryValue':'Phục hồi {value}{light}{stage}', 'daily.recoveryMissing':'Chưa có dữ liệu phục hồi{stage}',
    'daily.headerCold':'📊 Chỉ số hôm nay', 'daily.headerWarm':'📊 Chỉ số so với mức nền của bạn',
    'daily.calibrating':'ℹ️ Dữ liệu phục hồi WHOOP vẫn đang hiệu chỉnh. Các chỉ số phục hồi chỉ hiển thị giá trị, chưa đánh giá tốt hay xấu.',
    'daily.stageCold':' (đang xây dựng mức nền cá nhân)', 'daily.stageProvisional':' (đang xây dựng mức nền: {count}/{target})',
    'daily.metricMissing':'{emoji} {metric}: chưa có dữ liệu',
    'daily.metricCold':'{emoji} {metric}: {value}',
    'daily.metricReady':'{emoji} {metric}: {value}{baseline}{light}',
    'daily.baseline':' (mức nền {value})', 'daily.baselinePending':' (đang xây dựng mức nền)',
    'daily.trendHeadStrong':'📉 Lưu ý xu hướng (nhiều tín hiệu sinh lý cùng thay đổi)',
    'daily.trendHead':'📉 Lưu ý xu hướng',
    'daily.trendBoth':'liên tục lệch mức nền và xấu dần', 'daily.trendWorsening':'xấu dần qua từng ngày',
    'daily.trendSustained':'lệch mức nền {days} ngày liên tiếp',
    'daily.trendLine':'· {metric}: {kind} ({series})',
    'daily.trendMore':'· Thêm {count} chỉ số đang lệch mức nền',
    'daily.changeHead':'🔎 Điều đáng chú ý hôm nay',
    'daily.changeAbove':'cao hơn trung bình 30 ngày {percent}%',
    'daily.changeBelow':'thấp hơn trung bình 30 ngày {percent}%',
    'daily.changeLine':'· {emoji} {metric}: {value}, {comparison}{zscore}',
    'daily.changeLineSimple':'· {emoji} {metric}: {value}{zscore}',
    'daily.footer':'{date} · mức nền {count}/{target} bản ghi',
    'daily.late':'📮 Bản tóm tắt gửi muộn cho ngày {date}\n(Dữ liệu đến muộn hơn thường lệ nên bạn nhận được bản này vào lúc này.)\n\n',
    'weekly.titleNamed':'📅 Tổng kết tuần ({name})', 'weekly.titleNeutral':'📅 Tổng kết tuần',
    'weekly.range':'{start} – {end} · {days} ngày có dữ liệu',
    'weekly.metricMissing':'{metric}: chưa có dữ liệu', 'weekly.metricValue':'{metric}: {value}{comparison}',
    'weekly.best':'🏆 Ngày tốt nhất: {date}, phục hồi {value}',
    'weekly.worst':'🥀 Ngày thấp nhất: {date}, phục hồi {value}',
    'weekly.noPrevious':'(Chưa đủ dữ liệu của tuần trước để so sánh.)',
    'weekly.label.recovery_score':'💪 Phục hồi trung bình','weekly.label.sleep_performance':'📈 Hiệu quả giấc ngủ',
    'weekly.label.sleep_total':'🌙 Thời lượng ngủ','weekly.label.sleep_debt':'⏳ Điều chỉnh nợ ngủ',
    'weekly.label.hrv':'❤️ HRV','weekly.label.rhr':'💓 Nhịp tim nghỉ',
    'weekly.noComparison':' (không có dữ liệu tuần trước để so sánh)', 'weekly.flat':' (gần như không đổi so với tuần trước)',
    'weekly.aboveZero':' (↑ cao hơn tuần trước; mức nền bằng 0 nên không thể tính phần trăm)',
    'weekly.belowZero':' (↓ thấp hơn tuần trước; mức nền bằng 0 nên không thể tính phần trăm)',
    'weekly.moreMinutes':' (nhiều hơn tuần trước {minutes} phút)',
    'weekly.fewerMinutes':' (ít hơn tuần trước {minutes} phút)',
    'weekly.percentChange':' ({arrow} {percent}% so với tuần trước)',
    'narrative.recoveryFact':'phục hồi {value}', 'narrative.sleepFact':'giấc ngủ {value}',
    'narrative.facts':'{when}: {facts}. ', 'narrative.noFacts':'Tôi đã nhận dữ liệu {when} của bạn. ',
    'narrative.coldBaseline':'Mức nền cá nhân vẫn đang được xây dựng, nên các giá trị này chỉ được ghi nhận chứ chưa dùng để đánh giá mức thường ngày của bạn. ',
    'narrative.calibrating':'Dữ liệu phục hồi WHOOP cũng đang hiệu chỉnh; các giá trị này chưa phù hợp để làm mức nền. ',
    'narrative.coldAdvice':'Hãy giữ nếp sinh hoạt thường ngày. Khi có thêm dữ liệu, nhận định sẽ rõ hơn.',
    'narrative.metricsReady':'Các chỉ số {when} của bạn đã sẵn sàng. ',
    'narrative.flagged':'{metrics} khác đáng kể so với mức nền cá nhân và đáng theo dõi. ',
    'narrative.normal':'So với mức nền cá nhân, {when} không có thay đổi đáng chú ý. ',
    'narrative.missingBaseline':'Mức nền của {metrics} vẫn đang được xây dựng, nên tôi chưa đánh giá các chỉ số đó {when}. ',
    'narrative.trends':'{metrics} thay đổi liên tiếp; hãy quan sát thêm vài ngày. ',
    'narrative.ease':'{when}, bạn có thể giảm cường độ để cơ thể có thời gian phục hồi.',
    'narrative.maintain':'Hãy duy trì nhịp sinh hoạt hiện tại.',
    'narrative.today':'hôm nay', 'narrative.lastWeek':'tuần trước', 'narrative.thisWeek':'tuần này',
    'metric.recovery':'Phục hồi', 'metric.sleep_total':'Giấc ngủ', 'metric.slow_wave':'Giấc ngủ sâu',
    'metric.rem':'REM', 'metric.sleep_debt':'Điều chỉnh nợ ngủ',
    'metric.sleep_consistency':'Độ đều đặn giấc ngủ', 'metric.disturbance_count':'Số lần gián đoạn giấc ngủ',
    'metric.spo2':'Oxy máu', 'metric.skin_temp':'Nhiệt độ da', 'metric.strain':'Mức gắng sức',
    'metric.previous_day_strain':'Mức gắng sức hôm qua', 'metric.deep_sleep':'Giấc ngủ sâu',
    'metric.rem_sleep':'REM',
  }),
});
