export const BRIEFING_STATUS_CATALOG = Object.freeze({
  'zh-TW': {
    'briefingStatus.sourceHealthy':'負責檢查晨報的排程最近有正常運作。',
    'briefingStatus.sourceDegraded':'排程最近仍有執行，但檢查頻率可能比平常慢。',
    'briefingStatus.sourceOutage':'負責檢查晨報的排程最近沒有正常執行。',
    'briefingStatus.schedulerStale':'負責定時檢查的排程最近一次跑完是{ago}，所以我現在沒辦法保證下一次檢查什麼時候會發生。',
    'briefingStatus.nextCheck':'後續排程成功檢查、而且資料準備好之後就會處理。',
    'briefingStatus.delivered':'今天的簡報我已經發出來了，往上滑應該看得到。',
    'briefingStatus.waitingSleepOpen':'還在等這一晚的睡眠資料。WHOOP 要等這一段睡眠結束並結算之後才會給我數字。',
    'briefingStatus.waitingSleep':'還在等最新的睡眠資料進來 —— 我這邊目前沒有可以報告的新睡眠。',
    'briefingStatus.waitingScoring':'睡眠已經記錄到了，但 WHOOP 還沒給出完整的評分（恢復分數通常會晚一點）。沒有評分我不會硬算，那樣的數字不可靠。',
    'briefingStatus.tooSoon':'你剛起來不久（大約 {ago}），我會等超過 {minutes} 分鐘再發，讓數字穩定下來。',
    'briefingStatus.ready':'資料已經齊了，簡報還沒送出 —— 等後續排程成功檢查之後就會發出來。',
    'briefingStatus.staleMain':'我這邊的資料看起來可以做簡報了，但負責定時檢查的排程最近沒有跑（上一次跑完是{ago}）。',
    'briefingStatus.staleExplain':'所以問題不在你的資料，是沒有人去把它發出來。我沒辦法自己叫醒那個排程，也不想給你一個我保證不了的時間。',
    'briefingStatus.sentLate':'今天的簡報已經發出來了 —— 它比平常晚一點，因為資料比較晚才備齊。',
    'briefingStatus.missed':'那一份已經超過我會補發的時間，所以不會再送了。',
    'briefingStatus.missedExplain':'不是資料不見了 —— 是超過期限之後，一份太舊的報告對你已經沒有參考價值。下一次睡眠的簡報不受影響。',
    'briefingStatus.failed':'簡報已經做好了，但送出的時候失敗了。',
    'briefingStatus.failedRetry':'後續排程成功檢查之後會再試一次。',
    'briefingStatus.busy':'簡報正在處理中，稍等一下就會送出來。',
    'briefingStatus.waitingRecovery':'睡眠已經記錄到了，但對應的恢復資料還沒進來 —— 少了它我不會硬算。',
    'briefingStatus.windowExpired':'那一份已經過了我會補發的時限，所以現行設定不會再把它發出來。',
    'briefingStatus.windowExplain':'不是資料不見了 —— 是超過時限之後我就不再當成「今天的簡報」。下一次睡眠的簡報不受影響。',
    'briefingStatus.unknown':'我現在沒辦法確定今天簡報的狀態 —— 手邊的紀錄不足以下判斷。',
    'briefingStatus.agoMinutes':'{value} 分鐘前', 'briefingStatus.agoHours':'{value} 小時前',
    'briefingStatus.agoDays':'{value} 天前', 'briefingStatus.agoUnknown':'有一段時間了',
    'briefingStatus.soon':'不到半小時',
  },
  en: {
    'briefingStatus.sourceHealthy':'The schedule that checks your briefing has run recently.',
    'briefingStatus.sourceDegraded':'The schedule has run recently, though checks may be slower than usual.',
    'briefingStatus.sourceOutage':'The schedule that checks your briefing has not run normally recently.',
    'briefingStatus.schedulerStale':'The scheduled check last completed {ago}, so I cannot promise when the next check will happen.',
    'briefingStatus.nextCheck':'It will be processed after a future scheduled check succeeds and the data is ready.',
    'briefingStatus.delivered':'I have sent today’s briefing. You should find it above in this chat.',
    'briefingStatus.waitingSleepOpen':'I am waiting for tonight’s sleep data. WHOOP provides the numbers after the sleep ends and is scored.',
    'briefingStatus.waitingSleep':'I am waiting for new sleep data; there is no new sleep to report yet.',
    'briefingStatus.waitingScoring':'Your sleep was recorded, but WHOOP has not finished scoring it. Recovery often arrives later. I will not calculate a briefing from incomplete scores.',
    'briefingStatus.tooSoon':'You woke up about {ago}. I wait at least {minutes} minutes before sending so the numbers can settle.',
    'briefingStatus.ready':'The data is ready, but the briefing has not been sent. It will be handled after a scheduled check succeeds.',
    'briefingStatus.staleMain':'The data appears ready, but the scheduled check has not run recently (last completed {ago}).',
    'briefingStatus.staleExplain':'Your data is not the issue. I cannot restart the scheduler or promise when it will run again.',
    'briefingStatus.sentLate':'Today’s briefing was sent later than usual because the data arrived later.',
    'briefingStatus.missed':'That briefing is past the window for a late send, so it will not be sent now.',
    'briefingStatus.missedExplain':'The data is still there. The report is too old to be useful as a current briefing. Your next sleep briefing is unaffected.',
    'briefingStatus.failed':'The briefing was prepared, but delivery failed.',
    'briefingStatus.failedRetry':'A future successful scheduled check will retry delivery.',
    'briefingStatus.busy':'Your briefing is being processed. Please give it a little time.',
    'briefingStatus.waitingRecovery':'Your sleep was recorded, but its recovery data has not arrived. I will not calculate the briefing without it.',
    'briefingStatus.windowExpired':'That briefing is past the window for a late send and will not be sent under the current schedule.',
    'briefingStatus.windowExplain':'The data is still there, but the report is no longer treated as today’s briefing. Your next sleep briefing is unaffected.',
    'briefingStatus.unknown':'I cannot confirm the status of today’s briefing from the records available to me.',
    'briefingStatus.agoMinutes':'{value} minutes ago', 'briefingStatus.agoHours':'{value} hours ago',
    'briefingStatus.agoDays':'{value} days ago', 'briefingStatus.agoUnknown':'some time ago',
    'briefingStatus.soon':'less than half an hour ago',
  },
  vi: {
    'briefingStatus.sourceHealthy':'Lịch kiểm tra bản tóm tắt gần đây vẫn chạy bình thường.',
    'briefingStatus.sourceDegraded':'Lịch kiểm tra gần đây vẫn chạy, nhưng có thể chậm hơn thường lệ.',
    'briefingStatus.sourceOutage':'Lịch kiểm tra bản tóm tắt gần đây không chạy bình thường.',
    'briefingStatus.schedulerStale':'Lần kiểm tra theo lịch gần nhất hoàn tất cách đây {ago}, nên tôi không thể hứa khi nào sẽ có lần kiểm tra tiếp theo.',
    'briefingStatus.nextCheck':'Bản tóm tắt sẽ được xử lý khi lần kiểm tra theo lịch sau đó thành công và dữ liệu đã sẵn sàng.',
    'briefingStatus.delivered':'Tôi đã gửi bản tóm tắt hôm nay. Bạn có thể xem ở phía trên cuộc trò chuyện.',
    'briefingStatus.waitingSleepOpen':'Tôi đang chờ dữ liệu giấc ngủ đêm nay. WHOOP cung cấp số liệu sau khi giấc ngủ kết thúc và được chấm điểm.',
    'briefingStatus.waitingSleep':'Tôi đang chờ dữ liệu giấc ngủ mới; hiện chưa có giấc ngủ mới để báo cáo.',
    'briefingStatus.waitingScoring':'Giấc ngủ đã được ghi nhận, nhưng WHOOP chưa chấm điểm xong. Điểm phục hồi thường đến muộn hơn. Tôi sẽ không tính bản tóm tắt từ điểm chưa đầy đủ.',
    'briefingStatus.tooSoon':'Bạn mới thức dậy khoảng {ago}. Tôi chờ ít nhất {minutes} phút trước khi gửi để số liệu ổn định hơn.',
    'briefingStatus.ready':'Dữ liệu đã sẵn sàng nhưng bản tóm tắt chưa được gửi. Bản này sẽ được xử lý sau khi lần kiểm tra theo lịch thành công.',
    'briefingStatus.staleMain':'Dữ liệu có vẻ đã sẵn sàng, nhưng lịch kiểm tra gần đây không chạy (lần hoàn tất gần nhất cách đây {ago}).',
    'briefingStatus.staleExplain':'Vấn đề không nằm ở dữ liệu của bạn. Tôi không thể tự khởi động lại lịch hoặc hứa khi nào lịch sẽ chạy.',
    'briefingStatus.sentLate':'Bản tóm tắt hôm nay đã được gửi muộn hơn thường lệ vì dữ liệu đến muộn.',
    'briefingStatus.missed':'Bản tóm tắt đó đã qua thời hạn gửi bù nên sẽ không được gửi nữa.',
    'briefingStatus.missedExplain':'Dữ liệu vẫn còn. Báo cáo đã quá cũ để dùng như bản tóm tắt hiện tại. Bản sau giấc ngủ tiếp theo không bị ảnh hưởng.',
    'briefingStatus.failed':'Bản tóm tắt đã được chuẩn bị, nhưng gửi không thành công.',
    'briefingStatus.failedRetry':'Một lần kiểm tra theo lịch thành công sau đó sẽ thử gửi lại.',
    'briefingStatus.busy':'Bản tóm tắt của bạn đang được xử lý. Vui lòng chờ thêm một chút.',
    'briefingStatus.waitingRecovery':'Giấc ngủ đã được ghi nhận, nhưng dữ liệu phục hồi tương ứng chưa đến. Tôi sẽ không tính bản tóm tắt khi thiếu dữ liệu này.',
    'briefingStatus.windowExpired':'Bản tóm tắt đó đã quá thời hạn gửi bù và sẽ không được gửi theo lịch hiện tại.',
    'briefingStatus.windowExplain':'Dữ liệu vẫn còn, nhưng báo cáo không còn được xem là bản tóm tắt hôm nay. Bản sau giấc ngủ tiếp theo không bị ảnh hưởng.',
    'briefingStatus.unknown':'Tôi chưa thể xác nhận trạng thái bản tóm tắt hôm nay từ các ghi nhận hiện có.',
    'briefingStatus.agoMinutes':'{value} phút trước', 'briefingStatus.agoHours':'{value} giờ trước',
    'briefingStatus.agoDays':'{value} ngày trước', 'briefingStatus.agoUnknown':'đã một thời gian',
    'briefingStatus.soon':'chưa đến nửa giờ',
  },
});
