export const DATA_QUALITY_CATALOG = Object.freeze({
  'zh-TW': {
    'quality.title':'📊 WHOOP 資料狀態',
    'quality.noAuth':'尚未完成 WHOOP 授權。請輸入 /connect 連接帳號。',
    'quality.notStarted':'歷史資料：尚未開始',
    'quality.history':'歷史區間：{from} ～ {to}',
    'quality.coverage':'涵蓋天數：{days} 天（缺 {missing} 天，涵蓋率 {ratio}%）',
    'quality.sleep':'睡眠：{count} 筆', 'quality.recovery':'恢復：{count} 筆（已評分 {scored}）',
    'quality.cycles':'週期：{count} 筆', 'quality.workouts':'運動：{count} 筆',
    'quality.naps':'小睡：{count} 筆', 'quality.unscored':'未評分：{count} 筆',
    'quality.stale':'⚠️ 最新資料已落後 {days} 天',
    'quality.journal':'Journal 紀錄：{count} 筆',
    'quality.probeDone':'資料可用性檢查：已執行（{date}）',
    'quality.probePending':'資料可用性檢查：尚未執行',
    'quality.capabilities':'  可用 {supported}／部分 {partial}／不可用 {unavailable}／未知 {unknown}',
    'quality.backfill':'歷史同步：{status}', 'quality.backfillPending':'尚未開始',
    'quality.backfillComplete':'已完成', 'quality.backfillRunning':'進行中',
    'quality.resource':'  {resource}: {status}',
    'quality.resourceName.sleep':'睡眠','quality.resourceName.recovery':'恢復',
    'quality.resourceName.cycle':'週期','quality.resourceName.workout':'運動',
    'quality.resourceName.profile':'個人資料','quality.resourceName.body_measurement':'身體測量',
    'quality.resourceName.other':'其他資料',
    'quality.scopeMissing':'⚠️ WHOOP 權限不足：{scopes}',
    'quality.scopeName.workout':'運動資料', 'quality.scopeName.bodyMeasurement':'身體測量資料',
    'quality.scopeName.other':'其他資料',
    'quality.scopeAdvice':'請輸入 /connect 重新授權。現有簡報不受影響。',
  },
  en: {
    'quality.title':'📊 WHOOP data status',
    'quality.noAuth':'WHOOP authorization is incomplete. Use /connect to connect your account.',
    'quality.notStarted':'History: not started',
    'quality.history':'History: {from}–{to}',
    'quality.coverage':'Coverage: {days} days ({missing} missing; {ratio}% covered)',
    'quality.sleep':'Sleep: {count} records', 'quality.recovery':'Recovery: {count} records ({scored} scored)',
    'quality.cycles':'Cycles: {count} records', 'quality.workouts':'Workouts: {count} records',
    'quality.naps':'Naps: {count} records', 'quality.unscored':'Unscored: {count} records',
    'quality.stale':'⚠️ The latest data is {days} days behind',
    'quality.journal':'Journal: {count} entries',
    'quality.probeDone':'Data availability check: complete ({date})',
    'quality.probePending':'Data availability check: pending',
    'quality.capabilities':'  Available {supported} / partial {partial} / unavailable {unavailable} / unknown {unknown}',
    'quality.backfill':'Historical sync: {status}', 'quality.backfillPending':'not started',
    'quality.backfillComplete':'complete', 'quality.backfillRunning':'in progress',
    'quality.resource':'  {resource}: {status}',
    'quality.resourceName.sleep':'Sleep','quality.resourceName.recovery':'Recovery',
    'quality.resourceName.cycle':'Cycles','quality.resourceName.workout':'Workouts',
    'quality.resourceName.profile':'Profile','quality.resourceName.body_measurement':'Body measurements',
    'quality.resourceName.other':'Other data',
    'quality.scopeMissing':'⚠️ Missing WHOOP permissions: {scopes}',
    'quality.scopeName.workout':'workout data', 'quality.scopeName.bodyMeasurement':'body measurements',
    'quality.scopeName.other':'other data',
    'quality.scopeAdvice':'Use /connect to authorize again. Existing briefings are unaffected.',
  },
  vi: {
    'quality.title':'📊 Trạng thái dữ liệu WHOOP',
    'quality.noAuth':'Quyền truy cập WHOOP chưa hoàn tất. Dùng /connect để kết nối tài khoản.',
    'quality.notStarted':'Lịch sử: chưa bắt đầu',
    'quality.history':'Lịch sử: {from}–{to}',
    'quality.coverage':'Dữ liệu trong {days} ngày (thiếu {missing} ngày; bao phủ {ratio}%)',
    'quality.sleep':'Giấc ngủ: {count} bản ghi', 'quality.recovery':'Phục hồi: {count} bản ghi ({scored} đã chấm điểm)',
    'quality.cycles':'Chu kỳ: {count} bản ghi', 'quality.workouts':'Buổi tập: {count} bản ghi',
    'quality.naps':'Giấc ngủ ngắn: {count} bản ghi', 'quality.unscored':'Chưa chấm điểm: {count} bản ghi',
    'quality.stale':'⚠️ Dữ liệu mới nhất chậm {days} ngày',
    'quality.journal':'Journal: {count} ghi chép',
    'quality.probeDone':'Kiểm tra khả năng truy cập dữ liệu: hoàn tất ({date})',
    'quality.probePending':'Kiểm tra khả năng truy cập dữ liệu: đang chờ',
    'quality.capabilities':'  Có thể dùng {supported} / một phần {partial} / không thể dùng {unavailable} / chưa rõ {unknown}',
    'quality.backfill':'Đồng bộ lịch sử: {status}', 'quality.backfillPending':'chưa bắt đầu',
    'quality.backfillComplete':'hoàn tất', 'quality.backfillRunning':'đang thực hiện',
    'quality.resource':'  {resource}: {status}',
    'quality.resourceName.sleep':'Giấc ngủ','quality.resourceName.recovery':'Phục hồi',
    'quality.resourceName.cycle':'Chu kỳ','quality.resourceName.workout':'Buổi tập',
    'quality.resourceName.profile':'Hồ sơ','quality.resourceName.body_measurement':'Số đo cơ thể',
    'quality.resourceName.other':'Dữ liệu khác',
    'quality.scopeMissing':'⚠️ Thiếu quyền WHOOP: {scopes}',
    'quality.scopeName.workout':'dữ liệu tập luyện', 'quality.scopeName.bodyMeasurement':'số đo cơ thể',
    'quality.scopeName.other':'dữ liệu khác',
    'quality.scopeAdvice':'Dùng /connect để cấp quyền lại. Các bản tin hiện có không bị ảnh hưởng.',
  },
});
