export const OAUTH_CATALOG = Object.freeze({
  'zh-TW': Object.freeze({
    'oauth.unset.title':'授權', 'oauth.unset.heading':'請回到 Telegram',
    'oauth.unset.body':'輸入 /connect 取得新連結。',
    'oauth.ok.title':'連接完成','oauth.ok.heading':'✅ WHOOP 已連接',
    'oauth.ok.body':'你可以關掉這個分頁，回到 Telegram。資料同步完成之後，助理會通知你。',
    'oauth.denied.title':'授權未完成','oauth.denied.heading':'授權未完成',
    'oauth.denied.body':'你在 WHOOP 的頁面取消了授權，或授權沒有完成。回到 Telegram 輸入 /connect 可以重新取得一條連結。',
    'oauth.state_invalid.title':'連結已失效','oauth.state_invalid.heading':'這條連結已經失效',
    'oauth.state_invalid.body':'授權連結是一次性的，而且有時效。回到 Telegram 輸入 /connect 取得一條新的。',
    'oauth.identity.title':'無法確認帳號','oauth.identity.heading':'無法確認這是哪個 WHOOP 帳號',
    'oauth.identity.body':'為了避免把別人的資料算到你身上，這次授權已經中止，沒有儲存任何東西。回到 Telegram 輸入 /connect 再試一次。',
    'oauth.already_linked.title':'帳號已被連接','oauth.already_linked.heading':'這個 WHOOP 帳號已經連到另一個使用者',
    'oauth.already_linked.body':'請改用你自己的 WHOOP 帳號。回到 Telegram 輸入 /connect 再試一次。',
    'oauth.mismatch.title':'帳號不一致','oauth.mismatch.heading':'這個帳號先前連的是另一個 WHOOP 帳號',
    'oauth.mismatch.body':'換帳號會讓既有的健康資料被錯誤歸屬，因此擋下來了。需要換人請聯絡管理者。',
    'oauth.error.title':'暫時無法完成','oauth.error.heading':'暫時無法完成授權',
    'oauth.error.body':'這是系統端的暫時問題。回到 Telegram 輸入 /connect 稍後再試一次。',
    'oauth.not_found.title':'找不到','oauth.not_found.heading':'找不到這個頁面','oauth.not_found.body':'',
  }),
  en: Object.freeze({
    'oauth.unset.title':'Authorization', 'oauth.unset.heading':'Return to Telegram',
    'oauth.unset.body':'Use /connect for a new link.',
    'oauth.ok.title':'Connected','oauth.ok.heading':'✅ WHOOP connected',
    'oauth.ok.body':'You can close this tab and return to Telegram. Your assistant will notify you when the data sync finishes.',
    'oauth.denied.title':'Authorization incomplete','oauth.denied.heading':'Authorization incomplete',
    'oauth.denied.body':'Authorization was canceled or did not finish on WHOOP. Return to Telegram and use /connect for a new link.',
    'oauth.state_invalid.title':'Link expired','oauth.state_invalid.heading':'This link is no longer valid',
    'oauth.state_invalid.body':'Authorization links can be used only once and expire. Return to Telegram and use /connect for a new one.',
    'oauth.identity.title':'Account could not be verified','oauth.identity.heading':'WHOOP account could not be verified',
    'oauth.identity.body':'Authorization stopped to protect your data. Nothing was saved. Return to Telegram and try /connect again.',
    'oauth.already_linked.title':'Account already connected','oauth.already_linked.heading':'This WHOOP account is connected to another user',
    'oauth.already_linked.body':'Use your own WHOOP account. Return to Telegram and try /connect again.',
    'oauth.mismatch.title':'Account mismatch','oauth.mismatch.heading':'This account was linked to a different WHOOP account',
    'oauth.mismatch.body':'Switching accounts could assign existing health data to the wrong person, so it was blocked. Contact an administrator if ownership needs to change.',
    'oauth.error.title':'Temporarily unavailable','oauth.error.heading':'Authorization could not be completed',
    'oauth.error.body':'A temporary system issue occurred. Return to Telegram and try /connect again later.',
    'oauth.not_found.title':'Not found','oauth.not_found.heading':'Page not found','oauth.not_found.body':'',
  }),
  vi: Object.freeze({
    'oauth.unset.title':'Cấp quyền', 'oauth.unset.heading':'Vui lòng quay lại Telegram',
    'oauth.unset.body':'Dùng /connect để lấy liên kết mới.',
    'oauth.ok.title':'Đã kết nối','oauth.ok.heading':'✅ WHOOP đã kết nối',
    'oauth.ok.body':'Bạn có thể đóng trang này và quay lại Telegram. Trợ lý sẽ báo khi dữ liệu đồng bộ xong.',
    'oauth.denied.title':'Chưa cấp quyền xong','oauth.denied.heading':'Chưa cấp quyền xong',
    'oauth.denied.body':'Bạn đã hủy hoặc chưa hoàn tất cấp quyền trên WHOOP. Quay lại Telegram và dùng /connect để lấy liên kết mới.',
    'oauth.state_invalid.title':'Liên kết hết hiệu lực','oauth.state_invalid.heading':'Liên kết này không còn hiệu lực',
    'oauth.state_invalid.body':'Liên kết cấp quyền chỉ dùng một lần và có thời hạn. Quay lại Telegram và dùng /connect để lấy liên kết mới.',
    'oauth.identity.title':'Không thể xác minh tài khoản','oauth.identity.heading':'Không thể xác minh tài khoản WHOOP',
    'oauth.identity.body':'Quá trình cấp quyền đã dừng để bảo vệ dữ liệu của bạn. Không có gì được lưu. Quay lại Telegram và thử /connect lần nữa.',
    'oauth.already_linked.title':'Tài khoản đã được kết nối','oauth.already_linked.heading':'Tài khoản WHOOP này đã kết nối với người dùng khác',
    'oauth.already_linked.body':'Hãy dùng tài khoản WHOOP của chính bạn. Quay lại Telegram và thử /connect lần nữa.',
    'oauth.mismatch.title':'Tài khoản không khớp','oauth.mismatch.heading':'Tài khoản này từng liên kết với một tài khoản WHOOP khác',
    'oauth.mismatch.body':'Việc đổi tài khoản có thể khiến dữ liệu sức khỏe được gán sai người nên đã bị chặn. Hãy liên hệ quản trị viên nếu cần đổi chủ sở hữu.',
    'oauth.error.title':'Tạm thời chưa thể hoàn tất','oauth.error.heading':'Chưa thể hoàn tất cấp quyền',
    'oauth.error.body':'Hệ thống đang gặp sự cố tạm thời. Quay lại Telegram và thử /connect sau.',
    'oauth.not_found.title':'Không tìm thấy','oauth.not_found.heading':'Không tìm thấy trang này','oauth.not_found.body':'',
  }),
});
