/** Presentation-only copy for established proactive decisions. */
export const PROACTIVE_CATALOG = Object.freeze({
  'zh-TW': {
    'proactive.safety': '如果你覺得不舒服，建議考慮休息、就醫或諮詢醫療專業人員——我沒有能力做任何醫療判斷。',
    'proactive.notify': '留意一下：你的{metric}最近持續{direction}{level}，不是單一天的雜訊。\n\n{safety}',
    'proactive.followUp': '補充一下之前提到的觀察：{statement}\n（信心程度從 {fromStatus} 更新為 {toStatus}，會持續追蹤。）',
    'proactive.guardFallback': '你的生理數據最近有些變化，值得留意。',
    'proactive.question': '你的{metric}今天比平常{direction}{level}。{prompt}\n（直接回我就好，例如「喝了三杯」或「沒有」。我會記下來，之後就能對照著看。）',
    'proactive.direction.low': '偏低', 'proactive.direction.high': '偏高', 'proactive.direction.flat': '有變化',
    'proactive.level.strong': '，而且幅度不小', 'proactive.level.notable': '',
    'proactive.questionLevel.strong': '了不少', 'proactive.questionLevel.notable': '了一些',
    'proactive.prompt.alcohol': '昨天有喝酒嗎？',
    'proactive.prompt.sickness': '最近有沒有不舒服、感冒的感覺？',
    'proactive.prompt.travel': '昨天有搭飛機或跨時區旅行嗎？',
    'proactive.prompt.late_sleep': '昨晚是不是特別晚睡？',
    'proactive.prompt.stress': '最近是不是壓力特別大？',
    'proactive.prompt.caffeine': '昨天下午或晚上有喝咖啡、茶之類的嗎？',
    'proactive.prompt.late_meal': '昨天有吃宵夜或很晚才吃晚餐嗎？',
    'proactive.prompt.exercise_note': '昨天的運動是不是比平常吃力？',
    'proactive.prompt.other': '昨天有發生什麼特別的事嗎？',
    'proactive.associationStatement':'「{factor}」與隔天{metric}之間目前觀察到{direction}的關聯（r={r}，樣本 {count} 天，資料充分度{quality}）。這是個人層級觀察到的關聯，跟其他因素的影響無法完全分開。',
    'proactive.associationPositive':'正向', 'proactive.associationNegative':'負向',
    'proactive.quality.INSUFFICIENT':'不足', 'proactive.quality.LOW_CONFIDENCE':'低',
    'proactive.quality.MODERATE':'中等', 'proactive.quality.BETTER_SUPPORTED':'較高',
    'proactive.status.NEW':'新觀察', 'proactive.status.HYPOTHESIS':'初步假設',
    'proactive.status.EMERGING':'待確認', 'proactive.status.SUPPORTED':'已有支持',
    'proactive.status.WEAKENED':'支持減弱', 'proactive.status.RETIRED':'已取代',
    'metric.recovery': '恢復分數', 'metric.respiratory_rate': '呼吸率',
    'metric.sleep_debt': '睡眠債', 'metric.previous_day_strain': '前一天的 Strain',
  },
  en: {
    'proactive.safety': 'If you feel unwell, consider resting or speaking with a healthcare professional. I cannot make medical judgments.',
    'proactive.notify': 'A quick note: your {metric} has stayed {direction}{level} recently. This is more than a single-day change.\n\n{safety}',
    'proactive.followUp': 'An update on an earlier observation: {statement}\n(Confidence changed from {fromStatus} to {toStatus}; I will keep tracking it.)',
    'proactive.guardFallback': 'Some of your health measurements have changed recently and may be worth noticing.',
    'proactive.question': 'Your {metric} is {direction}{level} than usual today. {prompt}\n(Just reply, for example, “three drinks” or “no.” I will save your answer for future comparisons.)',
    'proactive.direction.low': 'lower', 'proactive.direction.high': 'higher', 'proactive.direction.flat': 'different',
    'proactive.level.strong': ' by a noticeable amount', 'proactive.level.notable': '',
    'proactive.questionLevel.strong': ' by quite a bit', 'proactive.questionLevel.notable': ' somewhat',
    'proactive.prompt.alcohol': 'Did you drink alcohol yesterday?',
    'proactive.prompt.sickness': 'Have you felt unwell or had cold symptoms recently?',
    'proactive.prompt.travel': 'Did you fly or cross time zones yesterday?',
    'proactive.prompt.late_sleep': 'Did you go to bed unusually late last night?',
    'proactive.prompt.stress': 'Have you been under more stress lately?',
    'proactive.prompt.caffeine': 'Did you have coffee or tea yesterday afternoon or evening?',
    'proactive.prompt.late_meal': 'Did you eat a late dinner or snack yesterday?',
    'proactive.prompt.exercise_note': 'Did yesterday’s exercise feel harder than usual?',
    'proactive.prompt.other': 'Did anything unusual happen yesterday?',
    'proactive.associationStatement':'{factor} and next-day {metric} currently show a {direction} association (r={r}, {count} days; data quality: {quality}). This is a personal observation, and other factors may also contribute.',
    'proactive.associationPositive':'positive', 'proactive.associationNegative':'negative',
    'proactive.quality.INSUFFICIENT':'insufficient', 'proactive.quality.LOW_CONFIDENCE':'low',
    'proactive.quality.MODERATE':'moderate', 'proactive.quality.BETTER_SUPPORTED':'better supported',
    'proactive.status.NEW':'new observation', 'proactive.status.HYPOTHESIS':'preliminary hypothesis',
    'proactive.status.EMERGING':'under review', 'proactive.status.SUPPORTED':'supported',
    'proactive.status.WEAKENED':'weaker support', 'proactive.status.RETIRED':'superseded',
    'metric.recovery': 'Recovery score', 'metric.respiratory_rate': 'Respiratory rate',
    'metric.sleep_debt': 'Sleep debt', 'metric.previous_day_strain': 'Previous day’s Strain',
  },
  vi: {
    'proactive.safety': 'Nếu thấy không khỏe, bạn nên cân nhắc nghỉ ngơi hoặc trao đổi với nhân viên y tế. Tôi không thể đưa ra nhận định y khoa.',
    'proactive.notify': 'Bạn có thể lưu ý: {metric} gần đây liên tục {direction}{level}, không chỉ thay đổi trong một ngày.\n\n{safety}',
    'proactive.followUp': 'Cập nhật thêm về nhận xét trước đó: {statement}\n(Mức độ tin cậy đổi từ {fromStatus} sang {toStatus}; tôi sẽ tiếp tục theo dõi.)',
    'proactive.guardFallback': 'Một số chỉ số sức khỏe của bạn gần đây đã thay đổi và có thể đáng lưu ý.',
    'proactive.question': '{metric} hôm nay {direction}{level} so với thường lệ. {prompt}\n(Bạn chỉ cần trả lời, ví dụ “ba ly” hoặc “không”. Tôi sẽ lưu lại để đối chiếu về sau.)',
    'proactive.direction.low': 'thấp hơn', 'proactive.direction.high': 'cao hơn', 'proactive.direction.flat': 'có thay đổi',
    'proactive.level.strong': ' khá rõ', 'proactive.level.notable': '',
    'proactive.questionLevel.strong': ' khá nhiều', 'proactive.questionLevel.notable': ' một chút',
    'proactive.prompt.alcohol': 'Hôm qua bạn có uống rượu bia không?',
    'proactive.prompt.sickness': 'Gần đây bạn có thấy không khỏe hoặc có triệu chứng cảm lạnh không?',
    'proactive.prompt.travel': 'Hôm qua bạn có bay hoặc đi qua múi giờ khác không?',
    'proactive.prompt.late_sleep': 'Tối qua bạn có đi ngủ muộn hơn thường lệ không?',
    'proactive.prompt.stress': 'Gần đây bạn có căng thẳng hơn không?',
    'proactive.prompt.caffeine': 'Chiều hoặc tối hôm qua bạn có uống cà phê hay trà không?',
    'proactive.prompt.late_meal': 'Hôm qua bạn có ăn tối hoặc ăn khuya muộn không?',
    'proactive.prompt.exercise_note': 'Buổi tập hôm qua có nặng hơn thường lệ không?',
    'proactive.prompt.other': 'Hôm qua có điều gì khác thường xảy ra không?',
    'proactive.associationStatement':'{factor} và {metric} ngày hôm sau hiện có mối liên hệ {direction} (r={r}, {count} ngày; chất lượng dữ liệu: {quality}). Đây là quan sát cá nhân và các yếu tố khác cũng có thể góp phần.',
    'proactive.associationPositive':'cùng chiều', 'proactive.associationNegative':'ngược chiều',
    'proactive.quality.INSUFFICIENT':'chưa đủ', 'proactive.quality.LOW_CONFIDENCE':'thấp',
    'proactive.quality.MODERATE':'trung bình', 'proactive.quality.BETTER_SUPPORTED':'được hỗ trợ tốt hơn',
    'proactive.status.NEW':'quan sát mới', 'proactive.status.HYPOTHESIS':'giả thuyết ban đầu',
    'proactive.status.EMERGING':'đang kiểm tra', 'proactive.status.SUPPORTED':'đã có dữ liệu hỗ trợ',
    'proactive.status.WEAKENED':'mức hỗ trợ giảm', 'proactive.status.RETIRED':'đã được thay thế',
    'metric.recovery': 'Điểm phục hồi', 'metric.respiratory_rate': 'Nhịp thở',
    'metric.sleep_debt': 'Thiếu ngủ tích lũy', 'metric.previous_day_strain': 'Strain ngày trước',
  },
});
